Repository IDEMSInternational/R-Instat, pull requests merged in 2021-12, with the labels that each got.

#6992 fixed convert to numeric form closing issue and updated install scripts
  installer/inno_install_script_32bit.iss
  installer/inno_install_script_64bit.iss
  instat/frmConvertToNumeric.vb
  instat/ucrDataView.vb
Labels: skip-releasenotes

#7018 Small fixes on opening the dataset from DataView Window and setted the activated links color under Start and Help consistent to the Recent
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: bug

#6878 Added Scale and Non-Negative buttons to the Transform dialog
  instat/dlgTransform.Designer.vb
  instat/dlgTransform.resx
  instat/dlgTransform.vb
Labels: feature

#7028 Added Script dialog
  instat/dlgScript.Designer.vb
  instat/dlgScript.vb
  instat/frmMain.resx
Labels: feature

#6966 Detect and remove empty columns and rows while importing data
  instat/dlgImportDataset.Designer.vb
  instat/dlgImportDataset.resx
  instat/dlgImportDataset.vb
Labels: feature

#7049 Fixes #7043 Added clear selection before adding columns as causes issue on linux
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
Labels: skip-releasenotes

#7057 Made the Message text box non-editable on the Remove Unused Levels dialog
  instat/dlgRemoveUnusedLevels.Designer.vb
Labels: bug

#6756 Added Dumbbell and Slope graphs
  instat/dlgLinePlot.designer.vb
  instat/dlgLinePlot.resx
  instat/dlgLinePlot.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#7056 Corrected the OK condition in Climatic > Check Data > QC Rainfall dialog
  instat/dlgClimaticCheckDataRain.vb
Labels: bug

#7055 Made the Try text box non-editable on the Calculator dialog
  instat/ucrTry.Designer.vb
Labels: bug

#6812 Added a dialog to prepare data for cluster analysis
  instat/dlgCluster.Designer.vb
  instat/dlgCluster.resx
  instat/dlgCluster.vb
Labels: feature

#7063 Updated fonts to save in options and to work in Linux
  instat/Interface/IGrid.vb
  instat/UserControl/ucrOutputPage.vb
  instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/clsInstatOptions.vb
  instat/clsRLink.vb
  instat/dlgOptions.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataFrameMetadata.vb
  instat/ucrDataView.vb
Labels: skip-releasenotes
