Repository IDEMSInternational/R-Instat, pull requests merged in 2021-11, with the labels that each got.

#6894 New sub dialog for Regex expression
  instat/instat.vbproj
  instat/sdgConstructRegexExpression.Designer.vb
  instat/sdgConstructRegexExpression.resx
  instat/sdgConstructRegexExpression.vb
Labels: skip-releasenotes

#6897 Added Truncate and Wrap as new features on the Transform dialogue.
  instat/dlgTransformText.Designer.vb
  instat/dlgTransformText.resx
  instat/dlgTransformText.vb
Labels: feature

#6899 Resized Transform dialogue.
  instat/dlgTransformText.Designer.vb
  instat/dlgTransformText.resx
Labels: bug

#6805 Added Treemap and Wordcloud in the Bar chart dialog
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.resx
  instat/dlgBarAndPieChart.vb
Labels: feature

#6906 Improved speed issues
  instat/Model/DataFrame/clsDataFramePage.vb
  instat/ucrDataView.vb
Labels: skip-releasenotes

#6910 Improved speed of filling grid
  instat/Model/DataFrame/clsDataFrame.vb
  instat/Model/DataFrame/clsDataFramePage.vb
  instat/ucrDataView.vb
Labels: skip-releasenotes

#6908 Updated refresh of data from the databook
  instat/Model/DataFrame/clsDataBook.vb
Labels: skip-releasenotes

#6923 fixed sizing of windows caused by DPI scaling
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrDataFrameMetadata.Designer.vb
  instat/ucrDataView.Designer.vb
Labels: skip-releasenotes

#6928 Empty dialog for cluster analysis
  instat/dlgClusterAnalysis.Designer.vb
  instat/dlgClusterAnalysis.resx
  instat/dlgClusterAnalysis.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6930 fixes #6787 - simple fix that swaps grids and labels on buttons
  instat/frmMain.vb
Labels: skip-releasenotes

#6918 Sorted out a developer error when opening fill missing values dialog
  instat/dlgInfillMissingValues.vb
Labels: bug

#6937 fixes #6902 deleting columns now look all visible columns and not jus…
  instat/ucrDataView.vb
Labels: skip-releasenotes

#6938 Updated tab selection when updating databook
  instat/Model/DataFrame/clsColumnMetaData.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.vb
Labels: skip-releasenotes

#6940 added back display info refresh
  instat/ucrDataView.vb
Labels: skip-releasenotes

#6888 Improved the Spells Dialogue following ICPAC Dialogue
  instat/dlgSpells.Designer.vb
  instat/dlgSpells.vb
Labels: Climatic

#6934 Fixed a bug when using column selection
  instat/dlgSelect.Designer.vb
  instat/dlgSelectColumns.resx
  instat/dlgSelectColumns.vb
  instat/sdgDataOptions.vb
Labels: bug

#6946 Adding an empty sub dialogue for the formatting of summary tables
  instat/instat.vbproj
  instat/sdgFormatSummaryTables.Designer.vb
  instat/sdgFormatSummaryTables.resx
  instat/sdgFormatSummaryTables.vb
Labels: skip-releasenotes

#6952 Bug fixed on the Element receiver under Climatic Check Data Rainfall
  instat/dlgClimaticCheckDataRain.Designer.vb
  instat/dlgClimaticCheckDataRain.resx
  instat/dlgClimaticCheckDataRain.vb
Labels: bug

#6959 Bug fixed when the Filter is applied in Climatic>Prepare>SPI/SPEI dialog
  instat/dlgSPI.vb
Labels: bug

#6979 Function definition for specific R Functions
  instat/clsRLink.vb
Labels: skip-releasenotes

#6974 Bug fixed when reading data sets from library
  instat/dlgFromLibrary.vb
Labels: bug

#6973 Changed the increment in the acceptable range controls in the Climatic Check Data Temperature dialog (plus other small enhancements)
  instat/dlgClimaticCheckDataTemperature.Designer.vb
  instat/dlgClimaticCheckDataTemperature.resx
  instat/dlgClimaticCheckDataTemperature.vb
Labels: feature

#6876 Improvements to Stack(Pivot Longer) dialog
  instat/dlgStack.Designer.vb
  instat/dlgStack.resx
  instat/dlgStack.vb
Labels: feature

#6892 Corrected and improved the Prepare > Column: Text > Split dialog
  instat/dlgSplitText.Designer.vb
  instat/dlgSplitText.resx
  instat/dlgSplitText.vb
Labels: bug

#6935 Changed the Infilling daily climatic dialog to use chillR::patch_daily_temps() plus minor improvement
  instat/dlgInfillMissingValues.Designer.vb
  instat/dlgInfillMissingValues.resx
  instat/dlgInfillMissingValues.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: Climatic

#6988 Added frmMain stub for Cluster Analysis dialog
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: skip-releasenotes

#6987 Fixed label display for the checkboxes in the Climsoft Wizard dialog
  instat/dlgClimsoftWizard.vb
Labels: Climatic

#6982 Added template option to the Structure > Circular > Define dialog
  instat/dlgCircular.Designer.vb
  instat/dlgCircular.vb
Labels: feature

#6995 New Tab-based Output Window
  Instat.sln
  instat/Enum/OutputType.vb
  instat/Model/Options/OutputFont.vb
  instat/Model/Output/clsOutputElement.vb
  instat/Model/Output/clsOutputList.vb
  instat/Model/Output/clsOutputLogger.vb
  instat/Model/Output/clsRScriptElement.vb
  instat/Translations.vb
  instat/UserControl/ucrOutputPage.Designer.vb
  instat/UserControl/ucrOutputPage.resx
  instat/UserControl/ucrOutputPage.vb
  instat/UserControl/ucrOutputPages.Designer.vb
  instat/UserControl/ucrOutputPages.resx
  instat/UserControl/ucrOutputPages.vb
  instat/clsInstatOptions.vb
  instat/clsRLink.vb
  instat/frmMain.vb
  instat/frmOutputWindow.Designer.vb
  instat/frmOutputWindow.sw-KE.resx
  instat/frmOutputWindow.vb
  instat/instat.vbproj
  instat/instat.vbproj.user
  instat/ucrOutputWindow.Designer.vb
  instat/ucrOutputWindow.resx
  instat/ucrOutputWindow.vb
Labels: feature

#7013 Added ggwordcloud R package
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes
