Repository IDEMSInternational/R-Instat, pull requests merged in 2021-07, with the labels that each got.

#6503 Added Paste New Data Frame dialog
  instat/dlgPasteNewDataFrame.Designer.vb
  instat/dlgPasteNewDataFrame.vb
Labels: feature

#6564 climatic data entry pasting bug fix
  instat/sdgClimaticDataEntry.vb
Labels: Climatic

#6584 Added empty placeholder for Copy Special dialog
  instat/dlgCopySpecial.Designer.vb
  instat/dlgCopySpecial.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6400 Implemented code for Wind/Pollution Rose dialogue
  instat/dlgWindPollutionRose.Designer.vb
  instat/dlgWindPollutionRose.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#6572 Added toggle button on Tool Bar to switch the main window to/from English
  instat/dlgOptions.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#6612 Aligned the save control in convert to circular dialog
  instat/dlgCircular.Designer.vb
Labels: bug

#6590 Added functionality to have key and link names increment after subsequent keys and links saving
  instat/clsRLink.vb
  instat/dlgAddKey.Designer.vb
  instat/dlgAddKey.resx
  instat/dlgAddKey.vb
  instat/dlgAddLink.Designer.vb
  instat/dlgAddLink.resx
  instat/dlgAddLink.vb
  instat/ucrInput.vb
  instat/ucrInputComboBox.vb
  instat/ucrSave.vb
Labels: feature

#6607 Bug fix: disable reogrid settings to not view text overflow
  instat/clsGridLink.vb
  instat/instat.vbproj
  instat/packages.config
  instat/ucrFactor.vb
  packages/DotNetZip.1.15.0/.signature.p7s
  packages/DotNetZip.1.15.0/lib/net40/DotNetZip.dll
  packages/DotNetZip.1.15.0/lib/net40/DotNetZip.xml
  packages/DotNetZip.1.15.0/lib/netstandard2.0/DotNetZip.dll
  packages/DotNetZip.1.15.0/lib/netstandard2.0/DotNetZip.xml
  packages/unvell.ReoGrid.dll.3.0.0/.signature.p7s
  packages/unvell.ReoGrid.dll.3.0.0/icon.png
  packages/unvell.ReoGrid.dll.3.0.0/lib/net40/unvell.ReoGrid.dll
  packages/unvell.ReoGrid.dll.3.0.0/lib/net40/unvell.ReoGrid.xml
  packages/unvell.ReoGrid.dll.3.0.0/lib/netcoreapp3.0/unvell.ReoGrid.dll
  packages/unvell.ReoGrid.dll.3.0.0/lib/netcoreapp3.0/unvell.ReoGrid.xml
Labels: bug

#6587 Bug fix: Displaying correct filter preview, corrected naming of filters and use of Not(!)
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrFilter.Designer.vb
  instat/ucrFilter.resx
  instat/ucrFilter.vb
Labels: bug

#6610 Aligned variable button and the receiver in graphics dialogs
  instat/ucrVariablesAsFactor.Designer.vb
  instat/ucrVariablesAsFactor.resx
Labels: bug

#6611 Aligning of the checkbox in Scatter plot options and possibly other places
  instat/ucrCheck.resx
Labels: bug

#6567 Copy from data view, columns and data frame grid to clipboard
  instat/dlgCopyDataFrame.Designer.vb
  instat/dlgCopyDataFrame.resx
  instat/dlgCopyDataFrame.vb
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrColumnMetadata.vb
  instat/ucrDataFrameMetadata.vb
  instat/ucrDataView.vb
Labels: feature

#6484 Added annotation feature into plots
  instat/clsGgplotDefaults.vb
  instat/dlgBarAndPieChart.vb
  instat/dlgBoxPlot.vb
  instat/dlgClimaticBoxPlot.vb
  instat/dlgClimaticStationMaps.vb
  instat/dlgCountryColouredMap.vb
  instat/dlgCumulativeDistribution.vb
  instat/dlgDescribeTwoVarGraph.vb
  instat/dlgDisplayTopN.vb
  instat/dlgDotPlot.vb
  instat/dlgGeneralForGraphics.vb
  instat/dlgHistogram.vb
  instat/dlgLinePlot.vb
  instat/dlgMosaicPlot.vb
  instat/dlgOptionsByContextBoxplot.vb
  instat/dlgPICSARainfall.vb
  instat/dlgParallelCoordinatePlot.vb
  instat/dlgRugPlot.vb
  instat/dlgScatterPlot.vb
  instat/dlgSummaryBarOrPieChart.vb
  instat/dlgTreemap.vb
  instat/dlgUseGraph.vb
  instat/sdgPlots.Designer.vb
  instat/sdgPlots.resx
  instat/sdgPlots.vb
Labels: feature

#6594 Added Tufte boxplots to the Boxplot, Jitter and Violin plot dialogue
  instat/dlgBoxPlot.designer.vb
  instat/dlgBoxPlot.resx
  instat/dlgBoxPlot.vb
Labels: feature

#6630 Enabled flexible positioning of labels on bar charts
  instat/sdgLayerOptions.Designer.vb
  instat/ucrGeom.vb
Labels: feature

#6632 Enabled all menus for copy and paste
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: skip-releasenotes

#6589 Added Density ridges to the Histogram dialogue
  instat/dlgHistogram.designer.vb
  instat/dlgHistogram.resx
  instat/dlgHistogram.vb
Labels: feature

#6642 Fixed bugs in distribution control with some column types (e.g. integer)
  instat/dlgFitModel.vb
  instat/dlgTwoVariableFitModel.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/ucrDistributions.vb
Labels: bug

#6628 Added Lan button into the Options dialog
  instat/dlgOptions.Designer.vb
  instat/dlgOptions.resx
  instat/dlgOptions.vb
Labels: feature

#6508 Improved the Summary Tables dialog
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.resx
  instat/dlgSummaryTables.vb
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature
