Repository IDEMSInternational/R-Instat, pull requests merged in 2021-04, with the labels that each got.

#6374 update download page to v0.7.0
  docs/Download.html
Labels: minor, skip-releasenotes

#6375 New Sub Dialog for Climatic Data Entry Dialog
  instat/instat.vbproj
  instat/sdgClimaticDataEntryOptions.Designer.vb
  instat/sdgClimaticDataEntryOptions.resx
  instat/sdgClimaticDataEntryOptions.vb
Labels: skip-releasenotes

#6376 Ensure that each of the 6 output windows has a unique header item name (needed for translations)
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrDataFrameMetadata.Designer.vb
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
  instat/ucrLog.Designer.vb
  instat/ucrOutputWindow.Designer.vb
  instat/ucrScript.Designer.vb
Labels: skip-releasenotes

#6319 Added Save Control to Transform Dialog
  instat/dlgTransformClimatic.Designer.vb
  instat/dlgTransformClimatic.resx
  instat/dlgTransformClimatic.vb
Labels: feature

#6386 Fixed presentation issues in Save Controls for String Distance, Make Date and Recode Factor dialogues
  instat/dlgMakeDate.vb
  instat/dlgRandomSample.resx
  instat/dlgRecodeFactor.Designer.vb
  instat/dlgRecodeFactor.resx
  instat/dlgStringDistance.Designer.vb
  instat/dlgStringDistance.resx
  instat/dlgStringDistance.vb
  instat/dlgStringHandling.resx
Labels: bug

#6385 Enhancement of convert to numeric on right click
  instat/clsGridROperations.vb
  instat/dlgFindNonnumericValues.vb
  instat/frmConvertToNumeric.Designer.vb
  instat/frmConvertToNumeric.resx
  instat/frmConvertToNumeric.vb
Labels: feature

#6392 Setting focus correctly in climatic summary dialogue
  instat/dlgClimaticSummary.vb
Labels: bug

#6395 Enabled Wind Rose pollution dialog
  instat/frmMain.Designer.vb
  instat/frmMain.resx
Labels: skip-releasenotes

#6387 Enhancement of cell right click
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.resx
  instat/ucrDataView.vb
Labels: bug

#6402 Allow comments to be added to columns and dataframes
  instat/dlgAddComment.Designer.vb
  instat/dlgAddComment.resx
  instat/dlgAddComment.vb
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataFrameMetadata.Designer.vb
  instat/ucrDataFrameMetadata.vb
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: feature

#6410 Fixed issue importing data from library
  instat/dlgImportDataset.vb
Labels: bug

#6408 Added menu for Setup data entry dialog
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: skip-releasenotes

#6412 Added new options to the Import dialog for importing CSV and text files
  instat/dlgImportDataset.vb
Labels: feature

#6414 Added option to compare by row in the Compare Columns dialogue
  instat/dlgCompareColumns.Designer.vb
  instat/dlgCompareColumns.resx
  instat/dlgCompareColumns.vb
Labels: feature

#6399 Enhancement of the Climatic Data Entry Dialog
  instat/dlgClimaticDataEntry.Designer.vb
  instat/dlgClimaticDataEntry.vb
  instat/sdgClimaticDataEntry.Designer.vb
  instat/sdgClimaticDataEntry.resx
  instat/sdgClimaticDataEntry.vb
  instat/sdgClimaticDataEntryOptions.Designer.vb
  instat/sdgClimaticDataEntryOptions.resx
  instat/sdgClimaticDataEntryOptions.vb
  instat/sdgCommentForDataEntry.Designer.vb
  instat/sdgCommentForDataEntry.resx
  instat/sdgCommentForDataEntry.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  packages/System.Data.SQLite.Core.1.0.113.7/.signature.p7s
Labels: Climatic

#6429 Bug fixes: Climatic data entry
  instat/dlgClimaticDataEntry.vb
  instat/sdgClimaticDataEntry.vb
  instat/sdgClimaticDataEntryOptions.vb
  instat/sdgCommentForDataEntry.Designer.vb
  instat/sdgCommentForDataEntry.resx
  instat/sdgCommentForDataEntry.vb
Labels: bug

#6432 Added import options for .dat file types
  instat/dlgImportDataset.vb
Labels: feature

#6435 Data entry setup implementation
  instat/dlgSetupForDataEntry.Designer.vb
  instat/dlgSetupForDataEntry.resx
  instat/dlgSetupForDataEntry.vb
  instat/frmMain.resx
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: Climatic
