Repository IDEMSInternational/R-Instat, pull requests merged in 2021-06, with the labels that each got.

#6510 Added 'Lan' language toggle button for subdialogs
  instat/ucrButtonsSubdialogue.designer.vb
  instat/ucrButtonsSubdialogue.resx
  instat/ucrButtonsSubdialogue.vb
Labels: feature

#6480 Fixed compilation warning related to adding and removing of event handler in ucrSave
  instat/ucrSave.vb
Labels: skip-releasenotes

#6507 Added a 'More...' option to the file menu and icon toolstrip
  instat/clsRecentFiles.vb
Labels: feature

#6533 Added tool tip text to English JSON file, to allow translation into French and Portuguese
  instat/translations/en/r_instat_not_menus.json
  instat/translations/translationsManuallyEntered.csv
Labels: skip-releasenotes

#6381 Bug fix: use of multiple factors on fill date gaps
  instat/dlgInfill.Designer.vb
  instat/dlgInfill.resx
  instat/dlgInfill.vb
  instat/static/InstatObject/R/data_object_R6.R
Labels: bug

#6552 Added tidyr to the list of packages loaded explicitly on start up
  instat/static/InstatObject/R/Rsetup.R
Labels: skip-releasenotes

#6517 Bug fixes: ensure comboxes to remember states in reopen of bar chart dialogue
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.resx
  instat/dlgBarAndPieChart.vb
Labels: bug

#6547 Adding the Kiswahili option to the list of Languages
  instat/dlgOptions.vb
Labels: feature

#6535 Added new R geoms: geom_density_ridges, geom_density_ridges2 and geom_density_ridges_gradient
  instat/ucrGeom.vb
Labels: feature

#6554 Added purrr to the list of packages loaded explicitly on start up
  instat/static/InstatObject/R/Rsetup.R
Labels: skip-releasenotes

#6548 Ensure that all dslabs package data sets can be imported
  instat/dlgFromLibrary.vb
Labels: bug

#6501 Added import of multiple text files; also ensured that Excel files are consistently imported correctly
  instat/dlgImportDataset.vb
Labels: feature

#6545 Included trace when counting number of days entered in data entry
  instat/sdgClimaticDataEntry.vb
Labels: bug

#6565 Swahili machine translations from CrowdIn
  instat/translations/sw/sw_r_instat_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#6560 Sorted out inconsistencies and improved menu item names under File and Describe menus
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: feature
