Repository IDEMSInternational/R-Instat, pull requests merged in 2021-09, with the labels that each got.

#6655 Improved Frequencies dialog
  instat/dlgFrequency.Designer.vb
  instat/dlgFrequency.resx
  instat/dlgFrequency.vb
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#6675 Added Display as Dotplot checkbox to Histogram dialog
  instat/dlgHistogram.designer.vb
  instat/dlgHistogram.resx
  instat/dlgHistogram.vb
Labels: feature

#6722 Added Export For Climsoft Dialog
  instat/dlgExportForClimsoft.Designer.vb
  instat/dlgExportForClimsoft.resx
  instat/dlgExportForClimsoft.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6704 Added Pivot Table dialog to the Describe> Two Variable menu
  instat/dlgPivotTable.Designer.vb
  instat/dlgPivotTable.resx
  instat/dlgPivotTable.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#6732 Added rug plot into point plot in Scatter Plot dialog
  instat/dlgScatterPlot.Designer.vb
  instat/dlgScatterPlot.resx
  instat/dlgScatterPlot.vb
Labels: feature

#6735 Corrected Spellings in Main form menus
  instat/frmMain.resx
Labels: bug

#6737 Re-arranged specific graphs in the Describe menu
  instat/frmMain.Designer.vb
  instat/frmMain.resx
Labels: feature

#6625 Refactored the Import dialog and ensure correct reading of multiple SPSS files
  instat/ApplicationEvents.vb
  instat/dlgImportDataset.vb
Labels: bug

#6733 Enabled New Data Frame dialog to 'try' running multiple lines
  instat/clsRCodeStructure.vb
  instat/clsRLink.vb
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.resx
  instat/dlgNewDataFrame.vb
  instat/ucrTry.vb
Labels: feature

#6736 Ensure that One variable Compare Models subdialog opens correctly
  instat/sdgOneVarCompareModels.vb
Labels: bug

#6734 Implemented the lollipop option in the Bar Chart dialog
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.resx
  instat/dlgBarAndPieChart.vb
Labels: feature

#6745 New empty script dialog
  instat/dlgScript.Designer.vb
  instat/dlgScript.resx
  instat/dlgScript.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6743 Renamed specific options in the Describe menu
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#6724 Improved smooth options in Line plot dialog.
  instat/dlgLinePlot.designer.vb
  instat/dlgLinePlot.resx
  instat/dlgLinePlot.vb
  instat/ucrGeom.vb
Labels: feature

#6708 Added smooth as a separate option in line plot dialog
  instat/dlgLinePlot.designer.vb
  instat/dlgLinePlot.resx
  instat/dlgLinePlot.vb
  instat/ucrGeom.vb
Labels: feature

#6747 Improved stacking feature and added unnest into stack dialog
  instat/dlgStack.Designer.vb
  instat/dlgStack.resx
  instat/dlgStack.vb
Labels: feature

#6546 Added extra buttons to simplify the use of the Script window
  instat/ucrScript.Designer.vb
  instat/ucrScript.resx
  instat/ucrScript.vb
Labels: feature

#6738 Added Heat Map Plot as a dialog in place of the Rug plot.
  instat/dlgRugPlot.Designer.vb
  instat/dlgRugPlot.resx
  instat/dlgRugPlot.vb
Labels: feature

#6706 Improved usability of the General Graphics dialog
  instat/dlgGeneralForGraphics.Designer.vb
  instat/dlgGeneralForGraphics.resx
  instat/dlgGeneralForGraphics.vb
  instat/sdgPlots.resx
Labels: feature

#6755 R Implementation of Column Selections
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/labels_and_defaults.R
Labels: feature

#6757 Allow multiple row factors in Pivot Table dialog
  instat/dlgPivotTable.Designer.vb
  instat/dlgPivotTable.resx
  instat/dlgPivotTable.vb
Labels: feature

#6769 Small fix to the layout of the xtab in the Plot options dialog
  instat/sdgPlots.resx
Labels: bug

#6773 Changed the name Specific to Specific Tables/Graphs in the main menu
  instat/frmMain.Designer.vb
  instat/frmMain.resx
Labels: feature

#6772 Allowed variables of any type as labels into the Plot subdialog geom_treemap_text
  instat/ucrGeom.vb
Labels: bug

#6766 Added shape receiver to the heat map dialogue
  instat/dlgRugPlot.Designer.vb
  instat/dlgRugPlot.resx
  instat/dlgRugPlot.vb
Labels: feature

#6555 Ensure that special characters display correctly in the Data View window
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: bug

#6725 Adjusted the position button, changed save control into a drop down and prefix of the new column in copy Row names dialog
  instat/dlgRownamesOrNumbers.Designer.vb
  instat/dlgRownamesOrNumbers.resx
  instat/dlgRownamesOrNumbers.vb
Labels: bug

#6750 Added reorder feature and minor bug fixes to the bar chart dialogue
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.resx
  instat/dlgBarAndPieChart.vb
Labels: feature

#6779 Made default (column) names consistent following tidyverse style guide
  instat/dlgAppend.vb
  instat/dlgAugment.vb
  instat/dlgBarAndPieChart.vb
  instat/dlgBoxPlot.vb
  instat/dlgClimaticBoxPlot.vb
  instat/dlgClimaticStationMaps.vb
  instat/dlgCombine.vb
  instat/dlgCombineText.vb
  instat/dlgConditionalQuantilePlot.vb
  instat/dlgConversions.vb
  instat/dlgCorrelation.vb
  instat/dlgDefineCRI.vb
  instat/dlgDisplayDailyData.vb
  instat/dlgDotPlot.vb
  instat/dlgEvapotranspiration.vb
  instat/dlgExtremesClimatic.vb
  instat/dlgGeneralForGraphics.vb
  instat/dlgGlance.vb
  instat/dlgHypothesisTestsCalculator.vb
  instat/dlgInfillMissingValues.vb
  instat/dlgInventoryPlot.vb
  instat/dlgJitter.vb
  instat/dlgLinePlot.vb
  instat/dlgOneVarUseModel.vb
  instat/dlgOtherRosePlots.vb
  instat/dlgPICSARainfall.vb
  instat/dlgParallelCoordinatePlot.vb
  instat/dlgPrincipalComponentAnalysis.vb
  instat/dlgRecodeNumeric.vb
  instat/dlgRegularSequence.vb
  instat/dlgScatterPlot.vb
  instat/dlgSeasonalPlot.vb
  instat/dlgTaylorDiagram.vb
  instat/dlgThemes.vb
  instat/dlgTreemap.vb
  instat/dlgWindrose.vb
  instat/sdgCorrPlot.vb
  instat/sdgOneVarCompareModels.vb
  instat/sdgSimpleRegOptions.vb
Labels: bug

#6790 Adding Column Selection on Prepare > Data Frame menu
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#6730 Improved One Way Frequencies dialog, added table save and extra parameters for 'frq' function
  instat/dlgOneWayFrequencies.Designer.vb
  instat/dlgOneWayFrequencies.resx
  instat/dlgOneWayFrequencies.vb
  instat/sdgOneWayFrequencies.Designer.vb
  instat/sdgOneWayFrequencies.resx
  instat/sdgOneWayFrequencies.vb
Labels: feature

#6763 Added Squish option to the Transform Text dialog
  instat/dlgTransformText.Designer.vb
  instat/dlgTransformText.resx
  instat/dlgTransformText.vb
Labels: feature

#6792 Fixing the Developer error when adding geom_abline layer
  instat/ucrGeom.vb
Labels: bug

#6709 Refactored the Recode Numeric dialog
  instat/dlgRecodeNumeric.Designer.vb
  instat/dlgRecodeNumeric.resx
  instat/dlgRecodeNumeric.vb
Labels: bug

#6785 Added geom_text_wordcloud and geom_text_wordcloud_area geoms.
  instat/ucrGeom.vb
Labels: feature

#6800 Adding the Help ID to the Two variable Pivot Table Dialogue
  instat/dlgPivotTable.vb
Labels: feature

#6806 Adding the Pivot Table to the Describe>Three Variable menu
  instat/dlgThreeVariablePivotTable.Designer.vb
  instat/dlgThreeVariablePivotTable.resx
  instat/dlgThreeVariablePivotTable.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/instat.vbproj
Labels: feature
