Repository IDEMSInternational/R-Instat, pull requests merged in 2021-05, with the labels that each got.

#6382 Created JSON file containing English text from all dialogs
  instat/translations/en/r_instat_menus.json
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#6444 Created JSON file containing English text from all dialogs including dynamic text
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#6446 New Crowdin updates
  instat/translations/fr/fr_r_instat_not_menus.json
Labels: skip-releasenotes

#6436 Adding flag fields on climatic data entry
  instat/dlgClimaticDataEntry.vb
  instat/sdgClimaticDataEntry.resx
  instat/sdgClimaticDataEntry.vb
  instat/sdgClimaticDataEntryOptions.resx
  instat/sdgClimaticDataEntryOptions.vb
  instat/sdgCommentForDataEntry.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: Climatic

#6448 Updated R packages to latest versions
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#6449 updated download page to v0.7.1
  docs/Download.html
Labels: skip-releasenotes

#6457 Small design fixes in Enter dialog
  instat/dlgEnter.resx
Labels: skip-releasenotes

#6428 Added missing value options into insert column(s)
  instat/dlgInsertColumn.Designer.vb
  instat/dlgInsertColumn.resx
  instat/dlgInsertColumn.vb
Labels: bug

#6461 Ensure that the previously selected station is displayed when reopening the Daily Data Entry dialog
  instat/ucrInputFactorLevels.vb
Labels: bug

#6458 Allow station coordinates, in station and shape files, to be checked and compared
  instat/dlgLocatingPointsInShapeFile.Designer.vb
  instat/dlgLocatingPointsInShapeFile.resx
  instat/dlgLocatingPointsInShapeFile.vb
Labels: Climatic

#6475 Added new empty dialog for selecting columns
  instat/dlgSelectColumns.Designer.vb
  instat/dlgSelectColumns.resx
  instat/dlgSelectColumns.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6452 Replaced the translation language radio buttons in the options dialogue with a combo box
  instat/dlgOptions.Designer.vb
  instat/dlgOptions.resx
  instat/dlgOptions.vb
Labels: feature

#6491 Improved presentation of French & Portuguese text in Convert Columns dialog
  instat/dlgConvertColumns.Designer.vb
  instat/dlgConvertColumns.resx
Labels: feature

#6214 Adding extreme value, generalized pareto and gumbel distributions
  instat/My Project/Resources.Designer.vb
  instat/My Project/Resources.resx
  instat/clsDistribution.vb
  instat/dlgRandomSample.designer.vb
  instat/dlgRandomSample.resx
  instat/dlgRandomSample.vb
  instat/dlgShowModel.Designer.vb
  instat/dlgShowModel.vb
  instat/sdgDistributionOptions.Designer.vb
  instat/sdgDistributionOptions.resx
  instat/sdgDistributionOptions.vb
  instat/static/InstatObject/R/Rsetup.R
  instat/ucrDistributions.Designer.vb
  instat/ucrDistributions.resx
  instat/ucrDistributions.vb
Labels: feature

#6497 Updated to R 4.1.0 and updated R packages
  installer/inno_install_script_32bit.iss
  installer/inno_install_script_64bit.iss
  instat/clsRLink.vb
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#6499 Corrected R package versions
  instat/static/InstatObject/R/Rsetup.R
Labels: skip-releasenotes

#6498 Set the language combo box in the Options dialog to be non-editable
  instat/dlgOptions.vb
Labels: bug

#6505 Added paste new data frame menu item
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: skip-releasenotes
