Repository IDEMSInternational/R-Instat, pull requests merged in 2021-02, with the labels that each got.

#6205 Adding quintiles, terciles and deciles to summary statistics
  instat/dlgClimaticSummary.vb
  instat/dlgColumnStats.vb
  instat/dlgDescribeTwoVariable.vb
  instat/sdgSummaries.Designer.vb
  instat/sdgSummaries.resx
  instat/sdgSummaries.vb
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#6219 Improved the Inventory Plot subdialog design and fixed the tab order
  instat/sdgInventoryPlot.Designer.vb
  instat/sdgInventoryPlot.resx
  instat/sdgInventoryPlot.vb
Labels: bug

#6218 Bug fix on try control giving unwanted warning in the output window
  instat/ucrTry.vb
Labels: bug, skip-releasenotes

#6223 Fixed bug in Inventory plot y-axis scales
  instat/static/InstatObject/R/data_object_R6.R
Labels: bug

#6210 Added checkmarks to four toolbar dropdown menu options ('Log Window', 'Script Window', 'Column Metadata' and 'Data Frame Metadata')
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#6237 Changed the default option position at the top on view data dialog
  instat/dlgView.resx
Labels: bug

#6220 Enabling Structured > Circular > Density Plot
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: skip-releasenotes
