Repository IDEMSInternational/R-Instat, pull requests merged in 2021-03, with the labels that each got.

#6231 Added more examples to the Construct option in the New Data Frame dialog
  instat/dlgNewDataFrame.resx
  instat/dlgNewDataFrame.vb
Labels: feature

#5873 Added memory of directory and filename to export & save dialogs
  instat/dlgExportDataset.Designer.vb
  instat/dlgExportDataset.resx
  instat/dlgExportDataset.vb
  instat/dlgExportGraphAsImage.Designer.vb
  instat/dlgExportGraphAsImage.resx
  instat/dlgExportGraphAsImage.vb
  instat/dlgExportRObjects.Designer.vb
  instat/dlgExportRObjects.resx
  instat/dlgExportRObjects.vb
  instat/dlgExportRWorkspace.Designer.vb
  instat/dlgExportRWorkspace.resx
  instat/dlgExportRWorkspace.vb
  instat/dlgSaveAs.Designer.vb
  instat/dlgSaveAs.resx
  instat/dlgSaveAs.vb
  instat/ucrFilePath.Designer.vb
  instat/ucrFilePath.vb
Labels: feature

#6245 Removing space between label and input in the save control
  instat/dlgFromLibrary.vb
Labels: bug

#6160 Automatically open R-Instat when user double-clicks on an associated data file
  instat/ApplicationEvents.vb
  instat/My Project/Application.Designer.vb
  instat/My Project/Application.myapp
  instat/frmMain.vb
  instat/instat.vbproj
Labels: feature

#6233 Inventory Plot dialog autofills defined elements, autofill implemented for multiple receivers, Is_Element property created for climatic dataframes
  instat/dlgInventoryPlot.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/ucrReceiver.vb
  instat/ucrReceiverSingle.vb
Labels: Climatic

#6252 If the combo box is updated from a non-string value (e.g. from a function object), then ensure that the combo box displays the correct string
  instat/clsCondition.vb
Labels: bug

#6260 Removed empty forms dlgCircularScatterPlot and dlgCircularRosePlot
  instat/dlgCircularRosePlot.Designer.vb
  instat/dlgCircularRosePlot.resx
  instat/dlgCircularRosePlot.vb
  instat/dlgCircularScatterPlot.Designer.vb
  instat/dlgCircularScatterPlot.resx
  instat/dlgCircularScatterPlot.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/instat.vbproj
Labels: skip-releasenotes

#6242 Small bug fixes on Import Dataset dialog
  instat/dlgImportDataset.Designer.vb
  instat/dlgImportDataset.resx
  instat/dlgImportDataset.vb
Labels: bug

#6256 Small issue fixes of the position button in RowName/Numbers dialog
  instat/dlgRownamesOrNumbers.resx
Labels: bug, skip-releasenotes

#6232 Changed save control into a combobox in the following dialogs: Numeric Cases, Enter, Duplicate, Count in Factor, Combine Factor, Find/Replace, Transform, Split, Combine, Distance
  instat/dlgCombine.vb
  instat/dlgCombineText.vb
  instat/dlgCountinFactor.vb
  instat/dlgDuplicateColumns.vb
  instat/dlgEnter.vb
  instat/dlgFindNonnumericValues.vb
  instat/dlgSplitText.vb
  instat/dlgStringDistance.vb
  instat/dlgStringHandling.vb
  instat/dlgTransformText.vb
Labels: feature

#6270 In the 'One Way Frequency' dialog box, allow multiple/single variables to be specified for 'Graph' or 'Both'
  instat/dlgOneWayFrequencies.Designer.vb
  instat/dlgOneWayFrequencies.resx
  instat/dlgOneWayFrequencies.vb
  instat/sdgOneWayFrequencies.vb
Labels: bug

#6272 Default (column) names now more concise by not including unnecessary number suffix
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#6248 Adjusted position of the numeric updown defining the number of facets in the Inventory sub dialog
  instat/sdgInventoryPlot.Designer.vb
  instat/sdgInventoryPlot.resx
Labels: bug

#6274 Better column names when importing NetCDF files
  instat/dlgOpenNetCDF.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: Climatic

#6280 Adding new windows form - sub-dialog for the Merge dialog
  instat/instat.vbproj
  instat/sdgMergeColumnsToInclude.Designer.vb
  instat/sdgMergeColumnsToInclude.resx
  instat/sdgMergeColumnsToInclude.vb
Labels: skip-releasenotes

#6257 Improved the date/time features of the Calculator
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#6172 Fixed bug in dlgAddLink triggered when dialog opened without a data frame loaded into R-Instat
  instat/dlgAddLink.vb
Labels: bug

#6286 Reversed change made in PR #6252 because it triggered a bug in the plot sub dialogue
  instat/clsCondition.vb
Labels: skip-releasenotes

#6154 Small bug fixes in Climatic Check Data Temperature dialog
  instat/dlgClimaticCheckDataTemperature.vb
Labels: Climatic

#6287 Added Summary checkbox to the Duplicates dialog
  instat/dlgDuplicates.Designer.vb
  instat/dlgDuplicates.resx
  instat/dlgDuplicates.vb
Labels: feature

#6288 Improved detection & display of data types
  instat/clsGridLink.vb
Labels: feature

#6296 Adding the json files containing the translations from xlf file
  instat/translations/instat.en-EN.json
  instat/translations/instat.fr-FR.json
Labels: skip-releasenotes

#6298 Renamed translation files to compatibility with CrowdIn integration
  instat/translations/en/en_r_instat_all.json
  instat/translations/fr/fr_r_instat_all.json
Labels: skip-releasenotes

#6299 corrected English translation file name
  instat/translations/en/r_instat_all.json
Labels: skip-releasenotes

#6304 Parameter positions added in "Merge - Column Select"
  instat/sdgMergeColumnsToInclude.vb
Labels: bug

#6307 split translation files into menu and non-menus
  instat/translations/en/r_instat_all.json
  instat/translations/en/r_instat_menus.json
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_all.json
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
Labels: skip-releasenotes

#6308 New Crowdin updates
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
Labels: skip-releasenotes

#6312 New Crowdin updates
  instat/translations/fr/fr_r_instat_menus.json
Labels: skip-releasenotes

#6315 Enabled viewing of last graph in one variable graph
  instat/static/InstatObject/R/data_object_R6.R
Labels: feature

#6316 Added five new rows to r_instat_menus JSON file
  instat/translations/en/r_instat_menus.json
Labels: skip-releasenotes

#6282 Fixing when OK is enabled in the Start of Rains dialog
  instat/dlgStartofRains.Designer.vb
  instat/dlgStartofRains.vb
Labels: Climatic

#6212 Added 'Swap Data and Metadata' option to 'View' menu
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#6332 Added an empty dialog for Locating points in shape file
  instat/dlgLocatingPointsInShapeFile.Designer.vb
  instat/dlgLocatingPointsInShapeFile.resx
  instat/dlgLocatingPointsInShapeFile.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6303 Fixing bug when clicking reset in the Duplicates dialog
  instat/dlgDuplicates.vb
Labels: bug

#6297 Display output message when creating a key or link in the Add Key or Add Link dialogs
  instat/dlgAddKey.vb
  instat/dlgAddLink.vb
  instat/static/InstatObject/R/Backend_Components/link.R
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#6222 Resolved issue when importing Excel files with missing data values
  instat/dlgImportDataset.vb
Labels: bug

#6333 Fixing the issue of multiple output in the duplicates dialog
  instat/dlgDuplicates.vb
Labels: bug

#6149 PICSA Rainfall graphs dialog: Added facet options and bug fixes
  instat/dlgPICSARainfall.Designer.vb
  instat/dlgPICSARainfall.vb
Labels: feature

#6340 Corrected a small spelling mistake in the `Help` menu (Acknowledgements).…
  instat/frmMain.Designer.vb
  instat/frmMain.resx
Labels: skip-releasenotes

#6342 Added "Fixed End Limit" and "Fixed Start Limit" options into Fill Date Gaps dialog
  instat/dlgInfill.Designer.vb
  instat/dlgInfill.resx
  instat/dlgInfill.vb
  instat/static/InstatObject/R/data_object_R6.R
Labels: feature

#6338 Added new dialog for finding points in a polygon
  instat/dlgLocatingPointsInShapeFile.Designer.vb
  instat/dlgLocatingPointsInShapeFile.resx
  instat/dlgLocatingPointsInShapeFile.vb
Labels: feature

#6276 Allowing more distributions for certain variable classes when modelling (the general case)
  instat/dlgFitModel.Designer.vb
  instat/dlgFitModel.resx
  instat/dlgFitModel.vb
  instat/static/.old/data_object.R
  instat/static/InstatObject/R/data_object_R6.R
  instat/ucrDistributions.vb
Labels: feature

#6309 Improved the One Variable Frequencies Graph
  instat/dlgOneWayFrequencies.resx
  instat/dlgOneWayFrequencies.vb
  instat/sdgOneWayFrequencies.Designer.vb
  instat/sdgOneWayFrequencies.resx
  instat/sdgOneWayFrequencies.vb
Labels: feature

#6235 Added options for non-numeric values when converting to numeric
  instat/clsGridROperations.vb
  instat/frmConvertToNumeric.Designer.vb
  instat/frmConvertToNumeric.resx
  instat/frmConvertToNumeric.vb
  instat/instat.vbproj
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.vb
Labels: feature

#6351 New dialog for grid data entry of daily climatic data
  instat/dlgClimaticDataEntry.Designer.vb
  instat/dlgClimaticDataEntry.resx
  instat/dlgClimaticDataEntry.vb
  instat/sdgClimaticDataEntry.Designer.vb
  instat/sdgClimaticDataEntry.resx
  instat/sdgClimaticDataEntry.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrDateTimePicker.vb
  instat/ucrInputFactorLevels.vb
Labels: Climatic

#6301 New dialog for climatic daily data entry
  instat/dlgClimaticDataEntry.Designer.vb
  instat/dlgClimaticDataEntry.resx
  instat/dlgClimaticDataEntry.vb
  instat/sdgClimaticDataEntry.Designer.vb
  instat/sdgClimaticDataEntry.resx
  instat/sdgClimaticDataEntry.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: Climatic

#6348 Enabled check stations in the main form and added new dialog for importing ERA5 data
  instat/dlgImportERA5Data.Designer.vb
  instat/dlgImportERA5Data.resx
  instat/dlgImportERA5Data.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6353 Added option to display menus in French.
  instat/Translations.vb
  instat/instat.vbproj
  instat/packages.config
  instat/translations/rInstatTranslations.db
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/.signature.p7s
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/buildTransitive/net20/Stub.System.Data.SQLite.Core.NetFramework.targets
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/buildTransitive/net40/Stub.System.Data.SQLite.Core.NetFramework.targets
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/buildTransitive/net45/Stub.System.Data.SQLite.Core.NetFramework.targets
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/buildTransitive/net451/Stub.System.Data.SQLite.Core.NetFramework.targets
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/buildTransitive/net46/Stub.System.Data.SQLite.Core.NetFramework.targets
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net20/System.Data.SQLite.dll
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net20/System.Data.SQLite.dll.altconfig
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net20/System.Data.SQLite.xml
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net40/System.Data.SQLite.dll
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net40/System.Data.SQLite.dll.altconfig
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net40/System.Data.SQLite.xml
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net45/System.Data.SQLite.dll
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net45/System.Data.SQLite.dll.altconfig
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net45/System.Data.SQLite.xml
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net451/System.Data.SQLite.dll
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net451/System.Data.SQLite.dll.altconfig
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net451/System.Data.SQLite.xml
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net46/System.Data.SQLite.dll
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net46/System.Data.SQLite.dll.altconfig
  packages/Stub.System.Data.SQLite.Core.NetFramework.1.0.113.3/lib/net46/System.Data.SQLite.xml
  packages/TranslateWinForm.1.0.1/.signature.p7s
  packages/TranslateWinForm.1.0.1/lib/net461/TranslateWinForm.dll
  packages/TranslateWinForm.1.0.1/lib/net461/TranslateWinForm.xml
Labels: feature

#6354 Added Import from CDS (Climate Data Store) dialog
  instat/dlgImportERA5Data.Designer.vb
  instat/dlgImportERA5Data.resx
  instat/dlgImportERA5Data.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#5971 Fixed small issues in the General Graphics dialogue
  instat/dlgGeneralForGraphics.Designer.vb
  instat/dlgGeneralForGraphics.resx
  instat/ucrAdditionalLayers.vb
  instat/ucrGeom.vb
Labels: bug

#6359 update R packages
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#6361 Implemented Add Comment dialog to tag suspect values
  instat/dlgAddComment.Designer.vb
  instat/dlgAddComment.resx
  instat/dlgAddComment.vb
  instat/frmEditor.vb
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: feature

#6367 Additional statistics tests and summaries for two variable fit model dialog
  instat/dlgTwoVariableFitModel.Designer.vb
  instat/dlgTwoVariableFitModel.vb
  instat/ucrTry.vb
Labels: feature

#6227 Enabling the test radio button in the Two variable fit model
  instat/dlgTwoVariableFitModel.Designer.vb
  instat/dlgTwoVariableFitModel.vb
  instat/ucrTry.vb
Labels: feature

#6290 Implemented dialog for Polar plot from Openair package
  instat/dlgOtherRosePlots.Designer.vb
  instat/dlgOtherRosePlots.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature
