Repository IDEMSInternational/R-Instat, pull requests merged in 2021-08, with the labels that each got.

#6573 Added back to back checkbox to the bar and pie chart dialogue
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.resx
  instat/dlgBarAndPieChart.vb
Labels: feature

#6648 Removing duplicated code in clsRlink
  instat/clsRLink.vb
Labels: skip-releasenotes

#6662 Adding the pivot table dialogue
  instat/dlgPivotTable.Designer.vb
  instat/dlgPivotTable.resx
  instat/dlgPivotTable.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#6649 Added geom_text_repel and geom_label_repel from ggrepel package into the R-Instat list of geoms
  instat/ucrGeom.vb
Labels: feature

#6673 Added sample as a summary into column statistics dialog
  instat/sdgSummaries.Designer.vb
  instat/sdgSummaries.resx
  instat/sdgSummaries.vb
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#6676 Bug fix: Passing the data name when copying data frames
  instat/dlgCopyDataFrame.vb
Labels: bug

#6654 Improve the geom_smooth() parameters
  instat/ucrGeom.vb
Labels: bug

#6694 Ensure correct visibility of Convert to Variate check box in the Three variable Modelling dialog
  instat/dlgThreeVariablesModelling.vb
Labels: bug
