Repository IDEMSInternational/R-Instat, pull requests merged in 2022-07, with the labels that each got.

#7595 Added Skim radio button and the Omit Missing button to the One Variable Summaries Dialog
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgOneVariableSummarise.vb
Labels: feature

#7593 Added more keys to the Integer Keyboard
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#7596 Ensured that date-type variables return `NA` if `sum` is performed in a calculation
  instat/static/InstatObject/R/Backend_Components/calculations.R
Labels: bug

#7569 In Row Numbers or Names dialog, if content is a row number, then ensured that the resulting variable is numeric
  instat/dlgRownamesOrNumbers.vb
Labels: bug

#7468 Added Lists in the New Data Frame dialog
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: enhancement

#7610 Ensured that R script with unclosed brackets treated as incomplete R statement
  instat/clsRLink.vb
Labels: bug

#7612 Ensured that Y-axis settings are persistent when closing/re-opening PICSA Rainfall dialog
  instat/dlgPICSARainfall.vb
  instat/sdgPICSARainfallGraph.vb
Labels: bug

#7628 Added a new empty dialogue to crop model sub-menu.
  instat/dlgApsimx.Designer.vb
  instat/dlgApsimx.resx
  instat/dlgApsimx.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#7629 Added filter for empty rows in Define New Filter dialog
  instat/static/InstatObject/R/data_object_R6.R
  instat/ucrFilter.Designer.vb
  instat/ucrFilter.vb
Labels: feature

#7631 Removed signmedian.test R package
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#7623 Improved the Describe > One Variable >Rating Data dialog
  instat/dlgRatingScales.Designer.vb
  instat/dlgRatingScales.vb
Labels: feature

#7641 Changes on View Menu
  instat/frmMain.Designer.vb
Labels: skip-releasenotes

#7638 Added prime keys to the Calculator dialog
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#6569 New Crowdin updates
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#7667 Removing unwanted base space in Conditional Quantile Plot dialog
  instat/dlgConditionalQuantilePlot.Designer.vb
Labels: bug

#7693 Increased the default maximum number of columns to display to 50
  instat/clsInstatOptionsDefaults.vb
Labels: feature

#7657 Added factor level order feature to the Describe > Two/Three Variable > Pivot Table dialog
  instat/dlgPivotTable.Designer.vb
  instat/dlgPivotTable.resx
  instat/dlgPivotTable.vb
  instat/dlgThreeVariablePivotTable.Designer.vb
  instat/dlgThreeVariablePivotTable.resx
  instat/dlgThreeVariablePivotTable.vb
  instat/instat.vbproj
Labels: feature

#7669 Enabled Tmin and Tmax autofill automatically in Transform dialog
  instat/dlgTransformClimatic.vb
Labels: bug

#7571 Ensured that dataframe can be renamed in Data Frame MetaData Grid
  instat/ucrDataFrameMetadata.vb
Labels: bug

#7682 Fixed the graphics axes issue in the General Graphics dialog.
  instat/dlgGeneralForGraphics.vb
Labels: bug

#7143 Added Chrolopleth map to the Heat Map dialog
  instat/dlgHeatMapPlot.Designer.vb
  instat/dlgHeatMapPlot.resx
  instat/dlgHeatMapPlot.vb
Labels: feature

#7680 Layout updates to PICSA menu
  instat/dlgPICSARainfall.Designer.vb
  instat/sdgPICSARainfallGraph.Designer.vb
  instat/sdgPICSARainfallGraph.vb
  instat/sdgPlots.Designer.vb
Labels: skip-releasenotes

#7520 Fixed minor bug in Climatic>Tidy and Examine>Data daily Dialog
  instat/dlgClimaticDataEntry.vb
  instat/sdgClimaticDataEntry.vb
Labels: Climatic

#7652 Modified the plot options in Mosaic Plot dialog
  instat/dlgMosaicPlot.Designer.vb
  instat/dlgMosaicPlot.resx
  instat/dlgMosaicPlot.vb
Labels: feature

#7696 Update json file with new text.
  instat/translations/en/r_instat_menus.json
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes
