Repository IDEMSInternational/R-Instat, pull requests merged in 2022-02, with the labels that each got.

#7191 Fixed position error when user changes the selected data frame in dialogs
  instat/ucrSave.vb
Labels: bug

#7201 Fixed the numeric and factor options mix in the Duplicate Column dialog
  instat/dlgDuplicateColumns.vb
Labels: bug

#7195 Ensure that list of recent files does not contain duplicates
  instat/clsRecentFiles.vb
Labels: bug

#7207 Enabled running multiple instances of R-Instat
  instat/My Project/Application.Designer.vb
  instat/My Project/Application.myapp
Labels: feature

#7214 Removed 'Use unique names for comparisons checkbox' in Compare Columns dialog
  instat/dlgCompareColumns.Designer.vb
  instat/dlgCompareColumns.vb
Labels: bug

#7218 Added 2 new geoms from the moderndive package
  instat/ucrGeom.vb
Labels: feature

#7211 Prevented text overflow in Column Metadata grid
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
Labels: bug

#7140 Small corrections to Prepare> Dataframe> Insert columns/rows dialog
  instat/dlgInsertColumn.Designer.vb
  instat/dlgInsertColumn.vb
Labels: bug

#7233 Added rcorpora and mlbench Packages for datasets
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#7219 Ensure output window always scrolls to bottom when new output is added
  instat/UserControl/ucrOutputPage.vb
Labels: bug

#7188 Fixing Reset issue in Prepare>Numeric>Transform dialog
  instat/dlgTransform.vb
Labels: bug

#7234 Added main form copy paste menus
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: skip-releasenotes

#7186 Added delete feature to the Data View window
  instat/Interface/IDataViewGrid.vb
  instat/Interface/IGrid.vb
  instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: feature

#7226 Added options to select columns by variable type, labelled variables, empty variables and NA variables
  instat/dlgSelect.vb
  instat/dlgSelectColumns.Designer.vb
  instat/dlgSelectColumns.vb
  instat/sdgDataOptions.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/labels_and_defaults.R
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#7252 Ensured that Delete Cells works correctly for Linux grids
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
  instat/ucrDataView.vb
Labels: bug

#7245 Added Pairs radio buttons to the Describe > Two Variables > Graphs dialog
  instat/dlgDescribeTwoVarGraph.Designer.vb
  instat/dlgDescribeTwoVarGraph.vb
Labels: feature
