Repository IDEMSInternational/R-Instat, pull requests merged in 2022-08, with the labels that each got.

#7708 New Crowdin updates
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/pt/pt_r_instat_menus.json
  instat/translations/sw/sw_r_instat_menus.json
Labels: skip-releasenotes

#7712 New Crowdin updates
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
Labels: skip-releasenotes

#7713 New Crowdin updates
  instat/translations/fr/fr_r_instat_menus.json
Labels: skip-releasenotes

#7717 Set 'counts' as default 'Stats' value in Histogram Plot dialog
  instat/dlgHistogram.vb
Labels: bug

#7720 New Crowdin updates
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#7711 In End of Rains Season dialog, increased capacity default from 1 to 100
  instat/dlgEndOfRainsSeason.vb
Labels: feature

#7726 Minor layout updates
  instat/dlgCorrelation.designer.vb
  instat/dlgDuplicateColumns.Designer.vb
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgSaveAs.Designer.vb
  instat/sdgCorrPlot.Designer.vb
  instat/sdgPlots.Designer.vb
  instat/ucrFilePath.Designer.vb
Labels: skip-releasenotes

#7572 Updated Histogram dialog's Plot Options to the new system
  instat/dlgHistogram.designer.vb
  instat/dlgHistogram.resx
  instat/dlgHistogram.vb
Labels: feature

#7732 New Crowdin updates
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#7730 Made PICSA Graphs sub-dialogs' titles consistent with PICSA Graphs dialogs
  instat/sdgPICSARainfallGraph.vb
Labels: bug

#7640 Minor adjustments on the ucrImput text Dataframe name control
  instat/dlgImportShapeFiles.Designer.vb
Labels: skip-releasenotes

#7644 Fixed a bug when reversing y-axis order in Density/Ridges plot in Histogram dialog
  instat/dlgHistogram.vb
Labels: bug

#7622 Fixes translation layout
  instat/dlgImportDataset.Designer.vb
  instat/dlgMakeDate.Designer.vb
  instat/dlgPICSARainfall.Designer.vb
  instat/sdgPICSARainfallGraph.Designer.vb
Labels: skip-releasenotes

#7735 New Crowdin updates
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#7734 Layout update to Plot Options sub dialog of PICSA rainfall graphs
  instat/ucrAxes.Designer.vb
Labels: skip-releasenotes

#7737 New Crowdin updates
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#7739 Revert "Fixed a bug when reversing y-axis order in Density/Ridges plot in Histogram dialog"
  instat/dlgHistogram.vb
Labels: skip-releasenotes

#7740 New Crowdin updates
  instat/translations/fr/fr_r_instat_not_menus.json
Labels: skip-releasenotes

#7748 Removed obsolete list of manually entered translations
  instat/translations/README.md
  instat/translations/translationsManuallyEntered.csv
Labels: skip-releasenotes

#7756 New Crowdin updates
  instat/translations/ru/ru_r_instat_menus.json
  instat/translations/ru/ru_r_instat_not_menus.json
Labels: skip-releasenotes

#7776 In the Prepare>Data Frame > Delete Column/ Rows dialog, after deleting rows ensure the new number of rows is displayed
  instat/ucrDataFrameLength.vb
Labels: bug

#7781 Improved behavior of position control in the Prepare > Data Frame > Row Numbers/Names dialog
  instat/dlgRownamesOrNumbers.vb
Labels: bug

#7785 Fixed bug with Degree option in Climatic > Prepare > Transform dialog
  instat/dlgTransformClimatic.vb
Labels: Climatic

#7769 Removed build warnings
  instat/frmOutputWindow.vb
  instat/ucrSelectorByDataFrameAddRemove.Designer.vb
Labels: skip-releasenotes

#7787 In the Prepare > DataFrame > Filter Row dialog, ensured that filter is updated when a dataset is deleted and reopened
  instat/dlgRestrict.vb
Labels: bug

#7793 New Crowdin updates
  instat/translations/fr/fr_r_instat_not_menus.json
Labels: skip-releasenotes

#7802 Cosmetic improvement to the stack dialog
  instat/dlgStack.vb
Labels: feature

#7796 Adjusted layout of Climatic menu dialogs to allow longer French text
  instat/DlgDefineClimaticData.Designer.vb
  instat/dlgAppend.Designer.vb
  instat/dlgClimaticCheckDataRain.Designer.vb
  instat/dlgConversions.Designer.vb
  instat/dlgExportToCPT.Designer.vb
  instat/dlgInventoryPlot.designer.vb
  instat/dlgOneWayFrequencies.Designer.vb
  instat/dlgStack.Designer.vb
  instat/sdgSaveColumnPosition.Designer.vb
Labels: feature

#7790 Included list variables in the Prepare> Column: Text Options dialog
  instat/dlgTransformText.vb
Labels: feature

#7813 Added reverse function to the calculator string keyboard
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#7783 Translate 'Code generated by dialog,' comment to the current language (e.g. French)
  instat/clsInstatOptions.vb
  instat/dlgOptions.vb
  instat/ucrButtons.Designer.vb
  instat/ucrButtons.vb
Labels: feature

#7809 New Crowdin updates
  instat/translations/en/r_instat_menus.json
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/ru/ru_r_instat_menus.json
  instat/translations/ru/ru_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes
