Repository IDEMSInternational/R-Instat, pull requests merged in 2022-12, with the labels that each got.

#7851 Added Apsimx Examples dialog
  instat/dlgApsimx.Designer.vb
  instat/dlgApsimx.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#7967 Added Expand button to the Stack dialog
  instat/dlgStack.Designer.vb
  instat/dlgStack.vb
Labels: feature

#7991 Added random sampling to Probability keyboard in Calculator dialog
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#7996 Added a new windows form for sdgSummaryThemes
  instat/instat.vbproj
  instat/sdgSummaryThemes.Designer.vb
  instat/sdgSummaryThemes.resx
  instat/sdgSummaryThemes.vb
Labels: skip-releasenotes

#7997 Fixed small build error
  instat/ucrCalculator.vb
Labels: skip-releasenotes

#7958 Added new options to Evapotranspiration dialog
  instat/dlgEvapotranspiration.Designer.vb
  instat/dlgEvapotranspiration.vb
  instat/instat.vbproj
  instat/sdgMissingOptionsEvapotranspiration.Designer.vb
  instat/sdgMissingOptionsEvapotranspiration.resx
  instat/sdgMissingOptionsEvapotranspiration.vb
Labels: feature

#7998 updated r packages
  instat/clsRLink.vb
  instat/static/InstatObject/R/InstallPackages.R
  instat/static/InstatObject/R/Rsetup.R
Labels: skip-releasenotes

#7995 Improved consistency/readability of Describe menu
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#8001 Disables maximum height for outputs in the output window
  instat/clsInstatOptions.vb
  instat/clsInstatOptionsDefaults.vb
  instat/dlgOptions.vb
Labels: skip-releasenotes

#8002 Added Multiple Response button in Frequency/Summary Tables
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.resx
  instat/dlgSummaryTables.vb
Labels: feature

#8003 Refactors Fit Model Keyboards and Hypothesis Tests Keyboards dialogs to use the new output system
  instat/dlgHypothesisTestsCalculator.vb
  instat/dlgModelling.vb
  instat/dlgOneVarFitModel.vb
Labels: skip-releasenotes

#8007 Ensured that the selected sheet in the Data View is maintained after reordering
  instat/Interface/IGrid.vb
  instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/dlgReorderDataFrame.vb
  instat/frmMain.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.vb
Labels: feature

#7925 Added summary statistics in output tables for date variables
  instat/static/InstatObject/R/Backend_Components/calculations.R
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#8010 Improved output viewer
  instat/Model/Output/clsOutputElement.vb
  instat/Model/Output/clsOutputLogger.vb
  instat/UserControl/ucrOutputPage.vb
  instat/UserControl/ucrOutputPages.vb
  instat/clsInstatOptionsDefaults.vb
  instat/clsRCodeStructure.vb
  instat/clsRLink.vb
  instat/dlgSummaryTables.vb
  instat/dlgThreeVariableFrequencies.vb
  instat/frmMain.vb
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#8028 Ensured that Column Structure dialog reopens with correct settings
  instat/dlgColumnStructures.vb
  instat/static/InstatObject/R/labels_and_defaults.R
Labels: bug

#8026 Added Complex Numbers keyboard to Calculator
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#8021 In Make Date dialog, ensured that default position of the resulting date variable is before the year variable (not after)
  instat/dlgMakeDate.vb
Labels: bug

#7951 Made small aesthetic fixes to Line Plot dialog
  instat/dlgLinePlot.designer.vb
  instat/dlgLinePlot.vb
  instat/translations/en/r_instat_not_menus.json
Labels: bug

#8016 Minor Change on Line Plot Dialog Design
  instat/dlgLinePlot.designer.vb
Labels: skip-releasenotes
