Repository IDEMSInternational/R-Instat, pull requests merged in 2022-01, with the labels that each got.

#7059 Dynamically resize info text in Data View
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: bug

#7035 Small corrections to the Evapotranspiration dialog design
  instat/dlgEvapotranspiration.Designer.vb
  instat/dlgEvapotranspiration.resx
  instat/dlgEvapotranspiration.vb
Labels: bug

#7053 Fixed error that triggered error dialog in Display Daily dialog
  instat/dlgDisplayDailyData.Designer.vb
  instat/dlgDisplayDailyData.resx
  instat/dlgDisplayDailyData.vb
Labels: bug

#6985 Improved the Climatic > Prepare > Conversions dialog
  instat/dlgConversions.Designer.vb
  instat/dlgConversions.resx
  instat/dlgConversions.vb
Labels: feature

#7038 In Open From Library dialog, open R script file and write to the Script Window, also added Niger script file
  instat/dlgImportDataset.vb
  instat/frmMain.vb
  instat/instat.vbproj
  instat/ucrScript.vb
Labels: feature

#7078 Rename Main output window tab
  instat/UserControl/ucrOutputPages.Designer.vb
  instat/UserControl/ucrOutputPages.vb
Labels: skip-releasenotes

#7085 Updated AutoScaleMode
  instat/sdgWindrose.Designer.vb
  instat/sdgWindrose.resx
  instat/ucrAdditionalLayers.Designer.vb
  instat/ucrAdditionalLayers.resx
  instat/ucrAxes.Designer.vb
  instat/ucrAxes.resx
  instat/ucrButtons.Designer.vb
  instat/ucrButtons.resx
  instat/ucrButtonsSubdialogue.designer.vb
  instat/ucrButtonsSubdialogue.resx
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCheck.Designer.vb
  instat/ucrCheck.resx
  instat/ucrColors.Designer.vb
  instat/ucrColors.resx
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrContinuousVerification.Designer.vb
  instat/ucrCore.Designer.vb
  instat/ucrCore.resx
  instat/ucrDataFrameLength.Designer.vb
  instat/ucrDataFrameLength.resx
  instat/ucrDataFrameMetadata.Designer.vb
  instat/ucrDataSelection.Designer.vb
  instat/ucrDataSelection.resx
  instat/ucrDataView.Designer.vb
  instat/ucrDateTimePicker.Designer.vb
  instat/ucrDayOfYear.Designer.vb
  instat/ucrDialogDisabled.Designer.vb
  instat/ucrDialogDisabled.resx
  instat/ucrDistributions.Designer.vb
  instat/ucrDistributions.resx
  instat/ucrDistributionsWithParameters.Designer.vb
  instat/ucrDistributionsWithParameters.resx
  instat/ucrELementTextControl.Designer.vb
  instat/ucrELementTextControl.resx
  instat/ucrElementLineControl.Designer.vb
  instat/ucrElementLineControl.resx
  instat/ucrElementRectControl.Designer.vb
  instat/ucrElementRectControl.resx
  instat/ucrFactor.Designer.vb
  instat/ucrFactor.resx
  instat/ucrFilePath.Designer.vb
  instat/ucrFilter.Designer.vb
  instat/ucrFilter.resx
Labels: skip-releasenotes

#7096 Save control combo box made visible
  instat/dlgCalculator.designer.vb
  instat/dlgClimaticStationMaps.Designer.vb
  instat/dlgOpenNetCDF.Designer.vb
  instat/ucrSave.Designer.vb
Labels: skip-releasenotes

#6916 Added Violin Plot, Box Plot, Line Graph and Dot Plot to Two Way Frequency Sub Dialog
  instat/sdgTwoWayFrequencies.Designer.vb
  instat/sdgTwoWayFrequencies.resx
  instat/sdgTwoWayFrequencies.vb
Labels: feature

#7090 Fixed bug on Climatic > Inventory Plot dialog
  instat/Model/Output/clsOutputElement.vb
  instat/UserControl/ucrOutputPage.vb
Labels: bug

#7097 Corrected typo identified by @shadrackkibet in PR #7051
  instat/ucrTry.vb
Labels: skip-releasenotes

#7098 Solving Build errors caused by frequency Sub Dialog
  instat/sdgTwoWayFrequencies.Designer.vb
  instat/sdgTwoWayFrequencies.resx
  instat/sdgTwoWayFrequencies.vb
Labels: skip-releasenotes

#7084 Fixing order of labels in the summary tables R code
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: bug

#7100 updated paths to use / instead of \ in some places for Linux version
  instat/clsRecentFiles.vb
  instat/dlgCompareModels.Designer.vb
  instat/dlgExportToCPT.vb
  instat/dlgImportDataset.vb
  instat/dlgOpenNetCDF.vb
  instat/dlgRandomSample.designer.vb
  instat/dlgSaveAs.Designer.vb
  instat/dlgSaveAs.resx
  instat/dlgSaveAs.vb
  instat/dlgShowModel.Designer.vb
  instat/frmMain.vb
  instat/sdgAddNewDistribution.Designer.vb
  instat/ucrDataView.vb
  instat/ucrFilePath.Designer.vb
Labels: skip-releasenotes

#7110 Fixed export dialog sizes
  instat/dlgExportDataset.Designer.vb
  instat/dlgExportDataset.resx
  instat/dlgExportGraphAsImage.Designer.vb
  instat/dlgExportGraphAsImage.resx
  instat/dlgExportRObjects.Designer.vb
  instat/dlgExportRObjects.resx
  instat/dlgExportRWorkspace.Designer.vb
  instat/dlgExportRWorkspace.resx
  instat/ucrFilePath.Designer.vb
Labels: skip-releasenotes

#7111 Fixed hiding of sheets when data frame is loaded to the data viewer
  instat/ucrDataView.vb
Labels: skip-releasenotes

#7118 Implemented the regex sub dialog under Prepare > Column:Text > Find/Replace Dialogue
  instat/dlgSplitText.Designer.vb
  instat/dlgSplitText.vb
  instat/dlgStringHandling.Designer.vb
  instat/dlgStringHandling.vb
  instat/sdgConstructRegexExpression.Designer.vb
  instat/sdgConstructRegexExpression.resx
  instat/sdgConstructRegexExpression.vb
Labels: feature

#7116 Changed checkbox label from Seed to Set Seed in Random subsets dialog
  instat/dlgRandomSubsets.Designer.vb
  instat/dlgRandomSubsets.vb
Labels: feature

#7033 Added column selection feature into the right clicks
  instat/Model/DataFrame/clsDataFrame.vb
  instat/Model/DataFrame/clsDataFrameFilter.vb
  instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrColumnMetadata.resx
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: feature

#7128 Variables in summary tables to be in order they are put in the receiver
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#7138 fixes small issue with labelling in the Climdex dialogue
  instat/dlgClimdexIndices.Designer.vb
Labels: skip-releasenotes

#7139 Resolved issues with layout of the Regular Sequence Dialog
  instat/dlgRegularSequence.designer.vb
  instat/dlgRegularSequence.vb
Labels: bug

#7144 Fixed button position issue in the Climatic Data Entry subdialog
  instat/sdgClimaticDataEntry.Designer.vb
Labels: bug

#7126 Resolved 'argument "x" is missing, with no default' error in Climatic>Boxplot dialog
  instat/dlgClimaticBoxPlot.vb
Labels: bug

#7136 Added recode options into recode numeric dialog
  instat/dlgRecodeNumeric.Designer.vb
  instat/dlgRecodeNumeric.resx
  instat/dlgRecodeNumeric.vb
Labels: feature

#7137 Sorted out efficiency and correctly labelling of quarter abbreviations in the use date dialog
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: bug

#7104 Added the facets angle on the inventory sub dialogue
  instat/dlgInventoryPlot.designer.vb
  instat/sdgInventoryPlot.Designer.vb
  instat/sdgInventoryPlot.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#7159 Making checkboxes visible in Use date dialog
  instat/DlgUseDate.Designer.vb
Labels: skip-releasenotes

#7156 Changed default on File > New Data Frame
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.vb
Labels: feature

#7117 Added Random number generator checkbox to Random samples
  instat/dlgRandomSample.designer.vb
  instat/dlgRandomSample.resx
  instat/dlgRandomSample.vb
Labels: feature

#7155 Small change to the facet label size on the Inventory subdialog
  instat/sdgInventoryPlot.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: bug

#7119 Corrected the Import Dialog Auto-size setting
  instat/dlgImportDataset.Designer.vb
Labels: skip-releasenotes

#7068 Added Degree button to the Climate>Prepare>Transform dialog
  instat/dlgTransformClimatic.Designer.vb
  instat/dlgTransformClimatic.resx
  instat/dlgTransformClimatic.vb
Labels: feature

#6884 Changed unstack (pivot wider) dialog to use pivot_wider function
  instat/dlgUnstack.Designer.vb
  instat/dlgUnstack.resx
  instat/dlgUnstack.vb
Labels: feature

#7167 Made Design Changes for Compare Columns Dialog
  instat/dlgCompareColumns.Designer.vb
Labels: skip-releasenotes

#7171 Improved Import from Library for Instat files
  instat/dlgImportDataset.vb
Labels: skip-releasenotes

#7169 Updated R packages and R version to 4.1.2
  instat/clsRLink.vb
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#7168 In Script dialog, correctly execute command copied to Output window
  instat/dlgScript.vb
Labels: bug

#7066 Implemented the Ctrl+C on the new Output Window
  instat/UserControl/ucrOutputPage.vb
Labels: bug

#7178 Adding the sub dialogue for formatting of Table
  instat/dlgFrequency.Designer.vb
  instat/dlgFrequency.vb
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.vb
  instat/sdgFormatSummaryTables.Designer.vb
  instat/sdgFormatSummaryTables.vb
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#7183 updated installation scripts and guide
  installer/Installer_Generation_Guide.md
  installer/inno_install_script_32bit.iss
  installer/inno_install_script_64bit.iss
Labels: skip-releasenotes
