Repository IDEMSInternational/R-Instat, pull requests merged in 2022-04, with the labels that each got.

#7334 Improved the Three Variable Pivot Table dialog
  instat/dlgThreeVariablePivotTable.Designer.vb
  instat/dlgThreeVariablePivotTable.vb
Labels: feature

#7325 Combined the Frequency and Summary Table dialogs into one dialog
  instat/dlgFrequency.Designer.vb
  instat/dlgFrequency.resx
  instat/dlgFrequency.sw-KE.resx
  instat/dlgFrequency.vb
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
Labels: feature

#7328 Export dialog enhancement
  instat/dlgExportDataset.Designer.vb
  instat/dlgExportDataset.vb
  instat/ucrFilePath.vb
Labels: feature

#7344 Fixed the bug on the result produced by PICSA when the Facets is by row or column
  instat/dlgPICSARainfall.vb
Labels: bug

#7348 Added an option to select variables by value labels in Select Columns dialog
  instat/dlgSelectColumns.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#7345 Added an option to Add Key for the new column in Prepare>Data Frame>Row Numbers/Names dialog
  instat/dlgConversions.vb
  instat/dlgRownamesOrNumbers.Designer.vb
  instat/dlgRownamesOrNumbers.vb
Labels: feature

#7352 Fixing limits issue in Temperature Quality Control dialog
  instat/dlgClimaticCheckDataTemperature.vb
Labels: bug

#7347 Improved Options by Context > Prepare > Merge Additional Data dialog
  instat/dlgMergeAdditionalData.Designer.vb
  instat/dlgMergeAdditionalData.vb
Labels: feature

#7336 Allow importing of data frames with same names from RDS files
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: bug

#7194 Added option on File > New Data Frame to provide variable names
  .gitignore
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.resx
  instat/dlgNewDataFrame.vb
Labels: feature

#7369 Fixed bug related to data frame length in Prepare > Numeric > Regular Sequence dialog
  instat/ucrDataFrameLength.vb
Labels: bug

#7326 Enahced the 'OK' and 'To Script' buttons to allow dialog to stay open after button clicked
  instat/instat.vbproj
  instat/ucrButtons.Designer.vb
  instat/ucrButtons.resx
  instat/ucrButtons.vb
  instat/ucrSplitButton.vb
Labels: enhancement

#7322 Made loading wide files into dialogs more efficient
  instat/ucrSelector.vb
Labels: feature

#7375 In grid, ensured that 'Levels/labels' option is only enabled when cell is a factor or ordered factor
  instat/ucrDataView.vb
Labels: bug

#7380 Enabled importing of data frames with duplicate column names
  instat/static/InstatObject/R/data_object_R6.R
Labels: feature

#7393 Fixed refreshing of Selector control when new column added
  instat/frmMain.vb
  instat/ucrSelector.vb
Labels: bug

#7390 Added With Replacement check box to Sample/Permute Rows dialog
  instat/dlgPermuteColumn.Designer.vb
  instat/dlgPermuteColumn.vb
Labels: feature

#7381 If error thrown when retrieving data frames from R, then handle error and display user message
  instat/Model/DataFrame/clsDataBook.vb
  instat/Model/DataFrame/clsDataFrame.vb
  instat/Model/DataFrame/clsDataFramePage.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/ucrDataView.vb
Labels: bug

#7321 Deleting labels in the new column created in Calculator and Transform Dialogues
  instat/dlgCalculator.vb
  instat/dlgTransform.vb
Labels: bug

#7403 Fixed bug related to deleting a dataframe in the Data View window
  instat/ucrSelector.vb
Labels: bug

#7417 In Prepare > Data Object > Rename Data Frame dialog, if original label exists, then include it
  instat/dlgRenameDataFrame.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#7395 Improves the use of long datasets with the Regular sequence dialog.
  instat/dlgRegularSequence.designer.vb
  instat/dlgRegularSequence.vb
Labels: feature

#7412 Ensure that parameters can be edited in Random Samples dialog
  instat/ucrDistributionsWithParameters.vb
Labels: bug

#7411 Minor improvements to the Contrasts dialog.
  instat/dlgContrasts.vb
Labels: feature

#7358 Refactors ucrFactor control and the dialogs that use it
  instat/dlgDefineCRI.Designer.vb
  instat/dlgDefineCRI.vb
  instat/dlgLabelsLevels.Designer.vb
  instat/dlgLabelsLevels.vb
  instat/dlgRecodeFactor.Designer.vb
  instat/dlgRecodeFactor.vb
  instat/dlgReferenceLevel.Designer.vb
  instat/dlgReferenceLevel.vb
  instat/dlgRemoveUnusedLevels.Designer.vb
  instat/dlgRemoveUnusedLevels.vb
  instat/dlgSurvivalObject.Designer.vb
  instat/dlgSurvivalObject.vb
  instat/mdlCoreControl.vb
  instat/sdgFiltersFromFactor.Designer.vb
  instat/sdgFiltersFromFactor.vb
  instat/sdgSelectMonth.Designer.vb
  instat/sdgSelectMonth.vb
  instat/ucrFactor.vb
  instat/ucrFilter.Designer.vb
  instat/ucrFilter.vb
Labels: skip-releasenotes

#7416 Minor Changes to Column:Text > Transform Dialogue
  instat/dlgTransformText.Designer.vb
  instat/dlgTransformText.vb
Labels: feature

#7399 In File > New Dataframe, added the Sequence data type to the new dataframe grid
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.vb
Labels: feature

#7424 In Column: Text > Split code, fixed a bug when another dataset is loaded in 'Into Binary Columns button'
  instat/dlgSplitText.vb
Labels: bug

#7362 Improvements to the Prepare> Factor> View/Delete Labels dialog
  instat/dlgViewLabelsAndLevels.Designer.vb
  instat/dlgViewLabelsAndLevels.vb
Labels: feature

#7423 Made the change to the metadata to update the Data Frame Metadata grid
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: bug

#7391 Moved View/Delete labels dialogue from Factor menu to Check Data menu
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#7429 Added R `skimr` package
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#7410 Improved the Describe > One Variable > Summarise dialog
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgOneVariableSummarise.vb
  instat/static/InstatObject/R/Backend_Components/calculations.R
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#7432 Fixes updating of the selector when the columns metadata changes
  instat/Model/DataFrame/clsColumnMetaData.vb
  instat/ucrSelector.vb
Labels: bug

#7220 Extended Prepare>Data Reshape>Transpose and ensured consistent with Tidyverse
  instat/dlgTransposeColumns.Designer.vb
  instat/dlgTransposeColumns.vb
Labels: feature
