Repository IDEMSInternational/R-Instat, pull requests merged in 2022-03, with the labels that each got.

#7216 Added an option to detect and report on empty columns into delete rows/columns dialog
  instat/dlgDeleteRowsOrColums.Designer.vb
  instat/dlgDeleteRowsOrColums.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#7261 Changed variable text colour when columns selection is applied
  instat/Model/DataFrame/clsDataFrame.vb
  instat/Model/DataFrame/clsDataFrameFilter.vb
  instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.vb
  instat/ucrSave.vb
Labels: feature

#7238 Added logical operations into Prepare>Column: Numeric>Transform dialog
  instat/dlgTransform.Designer.vb
  instat/dlgTransform.vb
Labels: feature

#7175 Added distributions to show model, random samples and general dialogs
  instat/dlgRandomSample.designer.vb
  instat/dlgRandomSample.vb
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
  instat/ucrDistributions.vb
  instat/ucrDistributionsWithParameters.Designer.vb
  instat/ucrDistributionsWithParameters.resx
  instat/ucrDistributionsWithParameters.vb
Labels: feature

#7263 Added options for renaming and deleting column selections
  instat/dlgDeleteObjects.Designer.vb
  instat/dlgDeleteObjects.vb
  instat/dlgRenameObjects.Designer.vb
  instat/dlgRenameObjects.vb
  instat/static/InstatObject/R/data_object_R6.R
Labels: feature

#7270 New Random Split dialog
  instat/dlgRandomSplit.Designer.vb
  instat/dlgRandomSplit.resx
  instat/dlgRandomSplit.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#7271 Fixed bug on the factor levels control being hidden in some dialogs
  instat/dlgCalculateTreatmentDifferences.Designer.vb
  instat/dlgClimaticDataEntry.Designer.vb
  instat/dlgCompareTreatmentLines.Designer.vb
  instat/dlgSetupForDataEntry.Designer.vb
  instat/ucrInputFactorLevels.Designer.vb
Labels: bug

#7276 Added option in Column Selection dialog to copy column selection into a separate data frame
  instat/dlgSelect.Designer.vb
  instat/dlgSelect.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#7184 Added up arrow button to Import Dataset Dialog
  instat/Resources/upward-arrow1.png
  instat/dlgImportDataset.Designer.vb
  instat/dlgImportDataset.resx
  instat/dlgImportDataset.vb
  instat/instat.vbproj
Labels: feature

#7247 Added delete of value labels to the Prepare > Column: Factor > View Levels/Labels dialogue using delete key in column metadata
  instat/Interface/IColumnMetaDataGrid.vb
  instat/Interface/IDataframeMetaDataGrid.vb
  instat/UserControls/DataGrid/Linux/ucrColumnMetadataLinuxGrid.vb
  instat/UserControls/DataGrid/Linux/ucrDataframeMetadataLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
  instat/dlgLabelsLevels.vb
  instat/dlgSelect.vb
  instat/dlgSelectColumns.vb
  instat/dlgViewLabelsAndLevels.Designer.vb
  instat/dlgViewLabelsAndLevels.vb
  instat/sdgDataOptions.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/ucrColumnMetadata.vb
  instat/ucrSelectorByDataFrameAddRemove.vb
Labels: feature

#7282 Added an option to include frequencies into the Prepare>Column: Factor> Factor Data Frame Dialogue
  instat/dlgFactorDataFrame.Designer.vb
  instat/dlgFactorDataFrame.vb
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature

#7268 Added Help to each right-click menu and also to the script window
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
  instat/ucrScript.Designer.vb
  instat/ucrScript.vb
  instat/ucrSelector.designer.vb
  instat/ucrSelector.vb
Labels: feature

#7302 fixes sizing of geom list with aes
  instat/UcrGeomListWithAes.designer.vb
  instat/ucrLayerParameters.Designer.vb
  instat/ucrLayerParamsControls.Designer.vb
  instat/ucrReceiverMetadataProperty.Designer.vb
Labels: bug

#7253 Hide drop empty rows checkbox when no file is selected in import dataset dialog
  instat/dlgImportDataset.Designer.vb
  instat/dlgImportDataset.resx
  instat/dlgImportDataset.vb
Labels: bug

#7291 Added delete labels to the new recoded factor column in Recode Factor Dialogue
  instat/dlgRecodeFactor.vb
  instat/ucrFactor.vb
Labels: bug

#7265 Naming and adding textboxes into Qc temperature dialog
  instat/dlgClimaticCheckDataTemperature.Designer.vb
  instat/dlgClimaticCheckDataTemperature.vb
Labels: Climatic

#7251 Improvements on the grid in the Contrasts dialog.
  instat/dlgContrasts.Designer.vb
  instat/dlgContrasts.vb
  instat/static/InstatObject/R/data_object_R6.R
Labels: feature

#7312 Corrected the error on the check values type in Non Numeric Dialogue
  instat/dlgFindNonnumericValues.vb
Labels: bug

#7283 Fixes small bug on the Climatic>Check Data>Inventory Plot dialogue
  instat/dlgInventoryPlot.vb
Labels: bug

#7300 Corrected the convert in Numeric Popup dialog
  instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
  instat/frmConvertToNumeric.Designer.vb
  instat/frmConvertToNumeric.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrDataView.vb
Labels: bug

#7314 Fixing bugs in the Lollipop Option in the Bar Chart dialog
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.vb
Labels: bug

#7278 Updated the data view info when selection is applied
  instat/Model/DataFrame/clsDataFrameFilter.vb
  instat/ucrDataView.vb
Labels: feature

#7342 Added double-click (and other small improvements) to Import from Library dialog
  instat/dlgFromLibrary.Designer.vb
  instat/dlgFromLibrary.vb
Labels: feature

#7231 Fixes the Regular Sequence dialog bug, refactors and improves its code
  instat/dlgDeleteRowsOrColums.Designer.vb
  instat/dlgRandomSample.designer.vb
  instat/dlgRegularSequence.designer.vb
  instat/dlgRegularSequence.vb
  instat/frmMain.vb
  instat/ucrDataFrameLength.Designer.vb
  instat/ucrDataFrameLength.vb
Labels: bug
