Repository IDEMSInternational/R-Instat, pull requests merged in 2022-05, with the labels that each got.

#7368 Removes redundant event and control in ucrInputs
  instat/dlgImportDataset.vb
  instat/dlgNewDataFrame.vb
  instat/dlgPopulationPyramids.Designer.vb
  instat/dlgPopulationPyramids.resx
  instat/dlgPopulationPyramids.sw-KE.resx
  instat/dlgPopulationPyramids.vb
  instat/instat.vbproj
  instat/ucrDistributionsWithParameters.vb
  instat/ucrInput.vb
  instat/ucrInputComboBox.vb
  instat/ucrInputTextBox.vb
  instat/ucrSaveGraph.Designer.vb
  instat/ucrSaveGraph.resx
  instat/ucrSaveGraph.sw-KE.resx
  instat/ucrSaveGraph.vb
Labels: skip-releasenotes

#7329 Added a feature to convert year from 2-digit year to 4-digit in the Climatic> Prepare> Conversions dialog
  instat/dlgConversions.Designer.vb
  instat/dlgConversions.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#7355 Fixed bug when colour is applied in the dataset from Data View window
  instat/Model/DataFrame/clsDataFramePage.vb
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/dlgColourbyProperty.Designer.vb
  instat/dlgColourbyProperty.vb
  instat/dlgMergeAdditionalData.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
Labels: bug

#7441 Selector bug fix
  instat/ucrDataFrame.vb
  instat/ucrSelector.vb
Labels: skip-releasenotes

#7453 In Climatic Maps dialog, improved error handling for invalid scripts
  instat/Model/Output/clsOutputElement.vb
  instat/dlgClimaticStationMaps.vb
Labels: feature

#7456 Creating New RFunction instance when declaring private class member in the dialogue to prevent exception when event handled before `SetDefaults()` called
  instat/dlgAddComment.vb
  instat/dlgAddLink.vb
  instat/dlgCircularDensityPlot.vb
  instat/dlgClimaticStationMaps.vb
  instat/dlgClimsoftWizard.vb
  instat/dlgDefineOptionsByContext.vb
  instat/dlgDuplicateColumns.vb
  instat/dlgExportDataset.vb
  instat/dlgExportRObjects.vb
  instat/dlgExportToWWR.vb
  instat/dlgFactorDataFrame.vb
  instat/dlgFindNonnumericValues.vb
  instat/dlgFitCorruptionModel.vb
  instat/dlgFitModel.vb
  instat/dlgFourVariableModelling.vb
  instat/dlgGeneralForGraphics.vb
  instat/dlgImportDataset.vb
  instat/dlgImportGriddedData.vb
  instat/dlgInventoryPlot.vb
  instat/dlgModelling.vb
  instat/dlgOptionsByContextFItModel.vb
  instat/dlgPlotRegion.vb
  instat/dlgRestrict.vb
  instat/dlgSeasonalPlot.vb
  instat/dlgSelect.vb
  instat/dlgSelectColumns.vb
  instat/dlgSpells.vb
  instat/dlgStack.vb
  instat/dlgThreeVariableFrequencies.vb
  instat/dlgThreeVariablesModelling.vb
  instat/dlgTimeSeriesPlot.vb
  instat/dlgViewLabelsAndLevels.vb
  instat/dlgViewObjects.vb
  instat/dlgWindPollutionRose.vb
Labels: skip-releasenotes

#7451 Removes redundant DataFrameChanged event in the data frame selector control
  instat/ucrDataFrame.vb
  instat/ucrDataFrameLength.vb
  instat/ucrInput.vb
  instat/ucrInputComboBox.vb
  instat/ucrNewColumnName.vb
  instat/ucrReorder.vb
  instat/ucrSelectorByDataFrame.vb
Labels: skip-releasenotes

#7464 Adding skimr description in install_packages.R
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#7466 Ensured correct order of added ranked variables in the Prepare>column:Numeric>Row Summaries dialog
  instat/dlgRowSummary.vb
Labels: bug

#7467 In Prepare>Data Reshape>Transpose Columns, ensured that New Names field is initially empty empty when Dialog is opened
  instat/dlgTransposeColumns.vb
Labels: bug

#7474 In Prepare > Add (Merge) Columns dialog, ensure that data frames with different key column names can still be merged
  instat/dlgMergeAdditionalData.vb
Labels: bug

#7470 Adding the random split dialog to form main
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: skip-releasenotes

#7501 Bug fix: correct maximum date when filling missing dates (ensure complete years option)
  instat/static/InstatObject/R/data_object_R6.R
Labels: bug

#7471 Ignore column selection when adding a new variable
  instat/static/InstatObject/R/data_object_R6.R
Labels: bug

#7482 Bug fixed: File > Close Data Book
  instat/frmMain.vb
Labels: bug

#7480 Made Annual button default and Station button to be last in Climatic Summaries dialog
  instat/dlgClimaticSummary.Designer.vb
  instat/dlgClimaticSummary.vb
Labels: feature

#7445 Combined the last dialog and last 10 dialogs tool bars into one
  instat/clsRecentFiles.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature
