Repository IDEMSInternational/R-Instat, pull requests merged in 2022-09, with the labels that each got.

#7827 Changed the maximum factor default value to 12 in One Variable Summary dialog
  instat/dlgOneVariableSummarise.vb
Labels: feature

#7824 Ensured that generated script correct even after dialog reload in Describe > Specific Tables/Graphs > Line Plot Option
  instat/dlgLinePlot.vb
Labels: bug

#7666 Ensured that 'Difference' checkbox has persistent state in Climatic > Check Data > QC Temperature dialog
  instat/dlgClimaticCheckDataTemperature.vb
Labels: bug

#7823 Improved the Probability and Integer keyboards in the Calculator
  instat/ucrCalculator.vb
Labels: feature

#7580 Updated Parallel Coordinate dialog's Plot Options to new drop-down button system
  instat/dlgParallelCoordinatePlot.Designer.vb
  instat/dlgParallelCoordinatePlot.resx
  instat/dlgParallelCoordinatePlot.vb
Labels: feature

#7830 New Crowdin updates
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
Labels: skip-releasenotes

#7835 Minor design change in the Frequency dialog
  instat/dlgOneWayFrequencies.Designer.vb
Labels: skip-releasenotes

#7838 Minor code change in QC Temperature Dialogue
  instat/dlgClimaticCheckDataTemperature.vb
Labels: skip-releasenotes

#7832 Added date time and time data types to column headers
  instat/Model/DataFrame/clsDataFramePage.vb
Labels: feature

#7839 Minor code and design changes in Filter Dialogue
  instat/ucrFilter.Designer.vb
  instat/ucrFilter.vb
Labels: skip-releasenotes

#7842 Minor code and design changes in Convert To Numeric Dailogue
  instat/frmConvertToNumeric.Designer.vb
  instat/frmConvertToNumeric.vb
Labels: skip-releasenotes

#7836 Added more distributions to General Fit Model dialog
  instat/clsRegressionDefaults.vb
  instat/dlgFitModel.vb
  instat/ucrDistributions.vb
Labels: feature

#7845 Minor design changes in Evapotranspiration Dialog.
  instat/dlgEvapotranspiration.Designer.vb
Labels: skip-releasenotes

#7844 New Crowdin updates
  instat/translations/en/r_instat_menus.json
  instat/translations/en/r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/ru/ru_r_instat_menus.json
  instat/translations/ru/ru_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#7864 Climatic translation fixes
  instat/dlgClimaticSummary.Designer.vb
  instat/sdgSummaries.Designer.vb
Labels: skip-releasenotes

#7868 Hid 'Paste New Columns' and 'Copy Special' options in Edit Menu
  instat/frmMain.Designer.vb
Labels: skip-releasenotes

#7685 Changed the Summary Table Percentages multiple factor to a single factor in Describe > Specific Tables/Graphs > Summary Tables Dialog
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.vb
Labels: feature

#7574 Corrected spacing and updated plot options to new system in Points (Scatter) Plot dialog
  instat/dlgScatterPlot.Designer.vb
  instat/dlgScatterPlot.resx
  instat/dlgScatterPlot.vb
Labels: bug

#7872 Added an empty new Window Number subdialog
  instat/instat.vbproj
  instat/sdgWindowNumber.Designer.vb
  instat/sdgWindowNumber.resx
  instat/sdgWindowNumber.vb
Labels: skip-releasenotes

#7875 Corrected "Code generated by the dialog," in English JSON file
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#7859 Ensured that button toggles from "Select All" To "Deselect All" in Factors sub-dialog
  instat/sdgFiltersFromFactor.vb
Labels: bug

#7784 Added counts with percentages option to summary function in Describe > Specific Tables/Graphs > Summary Tables dialog
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: feature

#7877 Readded 19 English text strings that CrowdIn mistakenly deleted in PR #7865
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#7878 New Crowdin updates
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/ru/ru_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#7880 New Crowdin updates
  instat/translations/es/es_r_instat_menus.json
  instat/translations/es/es_r_instat_not_menus.json
Labels: skip-releasenotes

#7882 Added Spanish language option
  instat/dlgOptions.vb
Labels: feature

#7788 Improved list names and default values in File > New Data Frame dialog
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.vb
Labels: feature

#7871 Added new features to script window
  .gitignore
  instat/instat.vbproj
  instat/packages.config
  instat/ucrScript.Designer.vb
  instat/ucrScript.resx
  instat/ucrScript.vb
Labels: feature
