Repository IDEMSInternational/R-Instat, pull requests merged in 2022-06, with the labels that each got.

#7492 Fixed bug in the Start of Rains Dialog
  instat/static/InstatObject/R/Backend_Components/calculations.R
Labels: bug

#7484 Added three Replace options in the Find/Replace dialog
  instat/dlgStringHandling.Designer.vb
  instat/dlgStringHandling.vb
Labels: feature

#7516 Fixed grid row sizes for shape file data frames
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: bug

#7523 Small improvement in the Prepare > Data Frame > Row Numbers/Names dialog
  instat/dlgRownamesOrNumbers.vb
Labels: feature

#7506 Added missing Geoms to the plot options in the Climatic>Mapping>Map sub dialog
  instat/dlgClimaticStationMaps.Designer.vb
  instat/dlgClimaticStationMaps.vb
Labels: feature

#7427 Fixed minor bug in Prepare>Data Frame>Rename Columns dialog
  instat/dlgName.vb
Labels: bug

#7526 Ensured that Column Metadata window opens with the default selected dataset in the Data View
  instat/ucrDataView.vb
Labels: feature

#7517 Adds a data book null check, in the data frame selector, to prevent design view error
  instat/ucrDataFrame.vb
Labels: skip-releasenotes

#7505 Improved plot options in Climatic > PICSA > Rainfall Graphs dialog
  instat/dlgPICSARainfall.Designer.vb
  instat/dlgPICSARainfall.resx
  instat/dlgPICSARainfall.vb
Labels: feature

#7527 Removed the Data Type restriction for the Prepare > Check Data > View/Delete Labels dialog
  instat/dlgViewLabelsAndLevels.vb
Labels: bug

#7500 Converted output produced to character or numeric in correlation dialog
  instat/dlgCorrelation.designer.vb
  instat/dlgCorrelation.vb
Labels: feature

#7335 Introduce AppImage build process
  installer/linux/appimage/.gitignore
  installer/linux/appimage/README.md
  installer/linux/appimage/docker/Dockerfile
  installer/linux/appimage/install_packages.R
  installer/linux/appimage/mono-config.patch
  installer/linux/appimage/r-instat.png
  installer/linux/appimage/recipe.yml
Labels: skip-releasenotes

#7469 updated R packages and versions
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#7537 Minor bug fix in column metadata with Linux
  instat/ucrDataView.vb
Labels: skip-releasenotes

#7185 Made Text file preview be shown on Linux Version
  instat/dlgImportDataset.vb
Labels: bug

#7544 Fixed bug in selecting of all factors
  instat/ucrFactor.vb
Labels: bug

#7508 Improved reordering of data frame tabs in Data View
  instat/Interface/IGrid.vb
  instat/Model/DataFrame/clsDataBook.vb
  instat/UserControls/DataGrid/Linux/ucrLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/dlgReorderDataFrame.Designer.vb
  instat/dlgReorderDataFrame.vb
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrColumnMetadata.Designer.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
  instat/ucrReorder.vb
Labels: feature

#7542 Added Point and Label options to the drop down menu in the Mapping dialog
  instat/dlgClimaticStationMaps.Designer.vb
  instat/dlgClimaticStationMaps.vb
Labels: feature

#7553 Added 2 more stats to the list of stats and geoms
  instat/ucrGeom.vb
Labels: feature

#7552 Added menu items under the selector add button
  instat/ucrSelectorByDataFrameAddRemove.Designer.vb
  instat/ucrSelectorByDataFrameAddRemove.resx
  instat/ucrSelectorByDataFrameAddRemove.vb
Labels: feature

#7490 Added Integer Keyboard to the Calculator
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#7531 Re-ordered codes in Scatter plot dialog to follow the normal system
  instat/dlgScatterPlot.vb
Labels: skip-releasenotes

#7548 Added labels for the unused levels in Prepare>Column: Factor>Remove Unused Levels dialog
  instat/dlgRemoveUnusedLevels.Designer.vb
Labels: feature

#7549 Fixed bugs in PICSA Rainfall Dialogue
  instat/dlgPICSARainfall.Designer.vb
  instat/dlgPICSARainfall.vb
Labels: bug

#7561 Fixed plotting bug on PICSA Rainfall Graph dialog
  instat/dlgPICSARainfall.vb
Labels: bug

#7567 Fixed bug related to reordering of data frame tabs in Data View
  instat/dlgReorderDataFrame.vb
  instat/frmMain.vb
  instat/ucrColumnMetadata.vb
  instat/ucrDataView.vb
Labels: bug
