Repository IDEMSInternational/R-Instat, pull requests merged in 2022-10, with the labels that each got.

#7899 In the Script window, improved the usability of brackets and quotes
  instat/ucrScript.Designer.vb
  instat/ucrScript.resx
  instat/ucrScript.vb
Labels: feature

#7826 Extended the Calculator Integer keyboard
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#7869 Extended the PCA dialog
  instat/dlgPrincipalComponentAnalysis.Designer.vb
  instat/dlgPrincipalComponentAnalysis.vb
  instat/sdgPrincipalComponentAnalysis.Designer.vb
  instat/sdgPrincipalComponentAnalysis.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#7867 Added Import From RapidPro Dialog
  instat/dlgImportFromRapidPro.Designer.vb
  instat/dlgImportFromRapidPro.vb
  instat/frmMain.Designer.vb
  instat/sdgImportFromRapidPro.Designer.vb
  instat/sdgImportFromRapidPro.vb
Labels: feature

#7894 Made variables of class bigz or bigq to type S in the data view
  instat/Model/DataFrame/clsDataFramePage.vb
Labels: skip-releasenotes

#7904 Improved Wakefield keyboard in the Calculator dialog
  instat/ucrCalculator.vb
Labels: feature

#7903 Added automatic indentation and code folding to the Script window
  instat/ucrScript.vb
Labels: feature

#7763 Fixed a bug when reversing y-axis order in Density/Ridges plot in Histogram dialog
  instat/dlgHistogram.vb
Labels: bug

#7846 Fixed translations in Export datasets dialog
  instat/dlgExportDataset.vb
Labels: skip-releasenotes

#7913 Adding Window Forms for Wordwrap dialog
  instat/dlgWordwrap.Designer.vb
  instat/dlgWordwrap.resx
  instat/dlgWordwrap.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#7919 In Column Metadata grid, display columns selected in DataView in red
  instat/UserControls/DataGrid/ReoGrid/ucrColumnMetadataReoGrid.vb
  instat/ucrColumnMetadata.vb
Labels: feature

#7900 In Data Frame Metadata grid, displays filtered columns and row in red
  instat/Model/DataFrame/clsDataBook.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataframeMetadataReoGrid.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/ucrDataFrameMetadata.vb
Labels: feature

#7637 Improved plot options in Options by Context dialog
  instat/dlgOptionsByContextBoxplot.Designer.vb
  instat/dlgOptionsByContextBoxplot.resx
  instat/dlgOptionsByContextBoxplot.vb
Labels: feature

#7921 Add Text in Json files
  instat/translations/en/r_instat_menus.json
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#7935 Fixed error message in Script window
  instat/ucrScript.vb
Labels: bug
