Repository IDEMSInternational/R-Instat, pull requests merged in 2022-11, with the labels that each got.

#7907 Improved Calculator Integer keyboard
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#7948 Added missing packages (coin, pingr, and vcdExtra)
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#7923 Added Options subdialog to Two variables, Frequency/summary and Column Summaries dialogs
  instat/dlgColumnStats.vb
  instat/dlgDescribeTwoVariable.Designer.vb
  instat/dlgDescribeTwoVariable.vb
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgOneVariableSummarise.vb
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.vb
Labels: feature

#7762 Fixed Line Plot dialog translation layout
  instat/dlgLinePlot.designer.vb
Labels: skip-releasenotes

#7954 Added more keys to the Prepare > Calculator > Transform Keyboard
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#7916 Ensured correct result from 3-way frequencies dialog
  instat/dlgThreeVariableFrequencies.vb
Labels: bug

#7965 Create empty Search dialog
  instat/dlgSearch.Designer.vb
  instat/dlgSearch.resx
  instat/dlgSearch.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#7946 In Import dialog, read a JSON file with equal lengths of lists
  instat/dlgImportDataset.vb
Labels: feature

#7937 Ensured big numbers can be displayed in Data View grid
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrColumnMetadata.vb
Labels: bug

#7928 Added extra options to the Bar and Pie Chart dialogs
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.vb
Labels: feature

#7715 Fixed bug in Climatic Summary dialog
  instat/dlgClimaticSummary.vb
Labels: bug

#7964 Enhanced New Dataframe dialog
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.vb
Labels: feature

#7912 Updated the help ids
  instat/dlgThreeVariableFrequencies.vb
  instat/dlgThreeVariablePivotTable.vb
  instat/sdgMissingOptions.vb
Labels: skip-releasenotes

#7853 Enhanced the output viewer to display html outputs (in windows machines), improve viewing of graphs and text outputs and improve processing of objects
  .gitignore
  instat/Enum/OutputType.vb
  instat/Enum/RObjectFormat.vb
  instat/Enum/RObjectTypeLabel.vb
  instat/Model/Output/clsOutputElement.vb
  instat/Model/Output/clsOutputLogger.vb
  instat/UserControl/ucrOutputPage.vb
  instat/UserControl/ucrOutputPages.vb
  instat/UserControls/Webview/Windows/CefRuntimeWrapper.vb
  instat/UserControls/Webview/Windows/ucrWebViewer.vb
  instat/UserControls/frmMaximiseOutput.Designer.vb
  instat/UserControls/frmMaximiseOutput.resx
  instat/UserControls/frmMaximiseOutput.vb
  instat/UserControls/ucrTextViewer.vb
  instat/app.manifest
  instat/clsInstatOptions.vb
  instat/clsInstatOptionsDefaults.vb
  instat/clsRCodeStructure.vb
  instat/clsRFunction.vb
  instat/clsRLink.vb
  instat/clsROperator.vb
  instat/clsRSyntax.vb
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgOneVariableSummarise.vb
  instat/dlgOpenNetCDF.vb
  instat/dlgOptions.Designer.vb
  instat/dlgOptions.vb
  instat/dlgRegularSequence.vb
  instat/dlgScatterPlot.vb
  instat/dlgSummaryTables.vb
  instat/dlgThreeVariableFrequencies.vb
  instat/dlgThreeVariablePivotTable.Designer.vb
  instat/dlgThreeVariablePivotTable.vb
  instat/dlgTwoWayFrequencies.vb
  instat/dlgViewLabelsAndLevels.vb
  instat/frmGraphDisplay.Designer.vb
  instat/frmGraphDisplay.sw-KE.resx
  instat/frmGraphDisplay.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
  instat/packages.config
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/labels_and_defaults.R
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrButtons.vb
  instat/ucrCore.vb
  instat/ucrInput.vb
  instat/ucrInputComboBox.vb
  instat/ucrSave.vb
  instat/ucrSaveModel.Designer.vb
  instat/ucrSaveModel.resx
  instat/ucrSaveModel.sw-KE.resx
  instat/ucrSaveModel.vb
  instat/ucrTry.vb
Labels: feature

#7718 Corrected misleading message in Tools > Install R package dialogue
  instat/dlgRPackages.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: bug

#7721 Added extra features to Climatic > Model > Extremes dialog
  instat/dlgExtremes.Designer.vb
  instat/dlgExtremes.vb
  instat/sdgExtremesMethod.Designer.vb
  instat/sdgExtremesMethod.vb
Labels: feature

#7905 Improved Hide/Unhide Dataframe(s) dialog
  instat/dlgHideDataframes.Designer.vb
  instat/dlgHideDataframes.vb
Labels: feature

#7933 Fixed small bugs in Add Prepare > Data Frame > Add (Merge) Data dialog
  instat/dlgMergeAdditionalData.vb
  instat/static/InstatObject/R/instat_object_R6.R
Labels: bug

#7972 Added new humidity elements into the Define Climatic Dialog
  instat/DlgDefineClimaticData.Designer.vb
  instat/DlgDefineClimaticData.vb
  instat/static/InstatObject/R/data_object_R6.R
Labels: feature

#7970 Added summaries for frequency data in the Calculator dialog
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#7973 Implemented Tab and arrow keys in Data grid
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
Labels: feature

#7893 Improved Define New Filter dialog
  instat/sdgFiltersFromFactor.Designer.vb
  instat/sdgFiltersFromFactor.vb
  instat/ucrFactor.Designer.vb
  instat/ucrFactor.vb
  instat/ucrFilter.Designer.vb
  instat/ucrFilter.vb
Labels: feature

#7909 Added create installer to workflows
  .github/workflows/CreateInstaller.yml
  inno_install_script_32bit.iss
  inno_install_script_64bit.iss
  instat/clsRLink.vb
  instat/frmMain.Designer.vb
  instat/static/InstatObject/R/InstallPackages.R
Labels: skip-releasenotes

#7990 Added support for viewing graphs in plotly through the last graph menu
  instat/UserControls/frmMaximiseOutput.vb
  instat/clsRLink.vb
  instat/frmMain.vb
  instat/static/InstatObject/R/instat_object_R6.R
Labels: feature
