Repository IDEMSInternational/R-Instat, pull requests merged in 2023-03, with the labels that each got.

#8159 Display R package help in output window rather than in browser
  instat/UserControls/Webview/Windows/ucrWebViewer.vb
  instat/UserControls/frmMaximiseOutput.vb
  instat/clsFileUrlUtilities.vb
  instat/dlgFromLibrary.vb
  instat/dlgHelpVignettes.vb
  instat/dlgHypothesisTestsCalculator.Designer.vb
  instat/dlgHypothesisTestsCalculator.vb
  instat/dlgModelling.Designer.vb
  instat/dlgModelling.vb
  instat/dlgUseModel.Designer.vb
  instat/dlgUseModel.vb
  instat/instat.vbproj
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrCalculator.vb
Labels: feature

#8169 Fixed regression bugs on the New Data Frame dialog
  instat/dlgNewDataFrame.vb
Labels: bug

#8168 Save summary, rather than save table in One, Two and Three-way frequency dialogs
  instat/dlgOneWayFrequencies.Designer.vb
  instat/dlgOneWayFrequencies.vb
  instat/dlgThreeVariableFrequencies.vb
  instat/dlgTwoWayFrequencies.vb
Labels: feature

#8174 Ensured buttons/options to display Script window show a tick when Script window is open
  instat/ucrButtons.vb
Labels: bug

#8179 Updated logging to use appData folder
  instat/NLog.config
  instat/clsRLink.vb
  instat/frmMain.vb
Labels: skip-releasenotes

#8178 Added locale to installed R
  instat/static/InstatObject/R/InstallPackages.R
Labels: bug

#8180 Added R packages
  instat/static/InstatObject/R/InstallPackages.R
  instat/static/InstatObject/R/Rsetup.R
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#8183 fixes for install
  instat/static/InstatObject/R/Rsetup.R
Labels: skip-releasenotes

#8192 Tell Git to ignore Newtonsoft Json NuGet package
  .gitignore
Labels: skip-releasenotes

#8204 Fixed a bug in Tidy Climatic Data dialog
  instat/dlgTidyDailyData.vb
  instat/static/InstatObject/R/instat_object_R6.R
Labels: bug

#8221 Ensured that rainfall is filled automatically in Climatic > Check QC Rainfall dialog
  instat/dlgClimaticCheckDataRain.vb
Labels: feature

#8226 Ensured that year fills automatically in PICSA dialogs
  instat/dlgPICSARainfall.vb
Labels: feature

#8218 Made day column the default button in the Climatic > Tidy > Tidy Daily Data dialog
  instat/dlgTidyDailyData.Designer.vb
  instat/dlgTidyDailyData.vb
Labels: feature

#8222 Ensure that Filter dialog always reopens in default state
  instat/dlgRestrict.vb
Labels: feature

#8211 Fixed factor level order for `summary-variable` type in Table Summaries
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: bug

#8228 Ensured that number of indices selected is in the middle of the message in Climdex Indices dialog
  instat/dlgClimdexIndices.Designer.vb
Labels: bug

#8235 Added agriTutorial package
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#8227 Added x2 (tmax) x3 (tmin) and x5 (rain) elements to Define Climatic dialog
  instat/DlgDefineClimaticData.Designer.vb
  instat/DlgDefineClimaticData.vb
Labels: feature

#8232 Hidden Low-Flow, Times series, Climatic, Procurement, and Options by context on Structured menu.
  instat/frmMain.Designer.vb
Labels: skip-releasenotes

#8208 Increased the number of preview lines in Import dialog
  instat/dlgImportDataset.vb
Labels: feature

#8233 Reset the Data View scroll bar to the top
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
Labels: feature

#8205 Added Selected Items label to multiple receivers for dialogs in Prepare > Databook sub menu
  instat/dlgDeleteDataFrames.Designer.vb
  instat/dlgDeleteDataFrames.vb
  instat/dlgDeleteObjects.Designer.vb
  instat/dlgDeleteObjects.vb
  instat/dlgHideDataframes.Designer.vb
  instat/dlgHideDataframes.vb
  instat/dlgReorderDataFrame.Designer.vb
  instat/dlgReorderDataFrame.vb
Labels: feature

#8181 Improved Rhelp for Model Menu Dialogs
  instat/dlgEnter.Designer.vb
  instat/dlgEnter.resx
  instat/dlgEnter.vb
  instat/dlgHypothesisTestsCalculator.Designer.vb
  instat/dlgHypothesisTestsCalculator.resx
  instat/dlgHypothesisTestsCalculator.vb
  instat/dlgModelling.Designer.vb
  instat/dlgModelling.resx
  instat/dlgModelling.vb
  instat/dlgUseModel.Designer.vb
  instat/dlgUseModel.resx
  instat/dlgUseModel.vb
Labels: feature

#8058 Translation Layout changes in New Data Frame dialogue
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgNewDataFrame.vb
Labels: skip-releasenotes

#8182 Improved the R code produced by One Variable > Summarise dialog
  instat/dlgOneVariableSummarise.vb
Labels: feature

#8191 Moved the log window to the first tab in the script window
  .gitignore
  instat/Translations.vb
  instat/clsRLink.vb
  instat/dlgFind.vb
  instat/dlgImportDataset.vb
  instat/dlgPrintPreviewOptions.vb
  instat/frmCommand.vb
  instat/frmLog.Designer.vb
  instat/frmLog.resx
  instat/frmLog.sw-KE.resx
  instat/frmLog.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/frmOutputWindow.vb
  instat/instat.vbproj
  instat/ucrButtons.vb
  instat/ucrLog.Designer.vb
  instat/ucrLog.resx
  instat/ucrLog.sw-KE.resx
  instat/ucrLog.vb
  instat/ucrScript.vb
Labels: feature

#8251 Added New R packages to R-Instat
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes
