Repository IDEMSInternational/R-Instat, pull requests merged in 2023-01, with the labels that each got.

#7976 Added apsimx package
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#8032 Included the new R Help button on all calculator keyboards
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#8005 Added Pair Plot Options sub dialog for Legend on Graphs dialog
  instat/dlgDescribeTwoVarGraph.Designer.vb
  instat/dlgDescribeTwoVarGraph.vb
  instat/instat.vbproj
  instat/sdgPairPlotOptions.Designer.vb
  instat/sdgPairPlotOptions.resx
  instat/sdgPairPlotOptions.vb
Labels: feature

#8012 Added nlog
  .gitignore
  instat/NLog.config
  instat/NLog.xsd
  instat/frmMain.vb
  instat/instat.vbproj
  instat/packages.config
Labels: skip-releasenotes

#8044 Added a Pascal key to the Calculator probability keyboard
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.vb
Labels: feature

#8047 When selecting data frames, allow user to add all/selected data frames
  instat/ucrSelectorAddRemove.designer.vb
  instat/ucrSelectorAddRemove.resx
  instat/ucrSelectorAddRemove.vb
Labels: feature

#8049 Minor bug fix of display of list variables from PR #8015
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
Labels: skip-releasenotes

#7581 Ensure that, when a dialog is reopened, only columns that still exist are shown in the list of selected columns
  instat/ucrReceiver.vb
  instat/ucrReceiverMultiple.vb
  instat/ucrSelector.vb
Labels: bug

#8059 Added factorize2 and primorial keys to the Calculator dialog integer keyboard
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#8057 Fixed small bugs in the Regular Sequence dialog
  instat/dlgRegularSequence.vb
Labels: bug

#8014 Further improvements to Output Viewer
  instat/Model/Output/clsOutputLogger.vb
  instat/Model/RCommand/clsPrepareFunctionsForGrids.vb
  instat/UserControl/ucrOutputPage.vb
  instat/UserControl/ucrOutputPages.vb
  instat/UserControls/frmMaximiseOutput.vb
  instat/clsRCodeStructure.vb
  instat/clsRLink.vb
  instat/dlgCombineforGraphics.vb
  instat/dlgOneVarFitModel.vb
  instat/dlgOneVarUseModel.vb
  instat/dlgTwoVariableUseModel.vb
  instat/dlgUseGraph.Designer.vb
  instat/dlgUseGraph.vb
  instat/dlgUseModel.vb
  instat/dlgViewGraph.Designer.vb
  instat/dlgViewGraph.vb
  instat/dlgViewObjects.vb
  instat/frmMain.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrButtons.vb
  instat/ucrReceiver.vb
  instat/ucrReceiverMultiple.vb
  instat/ucrReceiverSingle.vb
  instat/ucrSave.vb
Labels: bug

#8078 Added Text in Json file and Minor Modification on Some Dialog Design on Prepare Menu.
  instat/dlgConversions.Designer.vb
  instat/dlgDescribeTwoVarGraph.Designer.vb
  instat/dlgEndOfRainsSeason.Designer.vb
  instat/dlgFindNonnumericValues.Designer.vb
  instat/dlgHideDataframes.Designer.vb
  instat/dlgMergeAdditionalData.Designer.vb
  instat/dlgRandomSample.designer.vb
  instat/dlgRandomSubsets.Designer.vb
  instat/dlgStack.Designer.vb
  instat/dlgTransformText.Designer.vb
  instat/sdgMerge.Designer.vb
  instat/translations/en/r_instat_not_menus.json
  instat/ucrScript.Designer.vb
Labels: skip-releasenotes

#8076 Improvement of the code quality of receiver logic that checks that when a dialog is reopened, only columns that still exist are shown in the list of selected columns
  instat/ucrReceiver.vb
  instat/ucrReceiverMultiple.vb
  instat/ucrSelector.vb
Labels: skip-releasenotes

#8084 Updated Help Menu
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: bug

#8064 Added text on Json File and Minor Design on Correlation, New Data Frame Dialog and Data Options Sub dialog.
  instat/dlgCorrelation.designer.vb
  instat/dlgNewDataFrame.Designer.vb
  instat/dlgVisualizeData.Designer.vb
  instat/translations/en/r_instat_not_menus.json
  instat/ucrAxes.Designer.vb
Labels: skip-releasenotes

#8093 Fixed bug renaming columns in bug on Prepare > Data Frame > Rename
  instat/dlgName.vb
Labels: bug
