Repository IDEMSInternational/R-Instat, pull requests merged in 2023-02, with the labels that each got.

#8101 Redone the changes made in PR #7894 which reversed by PR #7924
  instat/Model/DataFrame/clsDataFramePage.vb
Labels: skip-releasenotes

#8097 Fixed the new variable name in Prepare> Column:Text> Split dialog
  instat/dlgSplitText.vb
Labels: bug

#8105 Ensured output from Summary dialog is correct
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgOneVariableSummarise.vb
Labels: bug

#8108 Ensured Rating Data dialog output correct
  instat/dlgRatingScales.vb
Labels: bug

#8056 Implemented plot options in Line Plot dialog
  instat/dlgLinePlot.designer.vb
  instat/dlgLinePlot.resx
  instat/dlgLinePlot.vb
Labels: feature

#8111 Implemented new output system in Describe >One variable >Frequencies dialog
  instat/dlgOneWayFrequencies.Designer.vb
  instat/dlgOneWayFrequencies.vb
Labels: feature

#8110 Ensured output for Two Way Frequencies dialog is correct
  instat/dlgTwoWayFrequencies.vb
Labels: bug

#8113 Ensured Three-way Frequency dialog output is correct
  instat/dlgThreeVariableFrequencies.vb
Labels: bug

#8112 Added R packages 'primes' and 'Zseq'
  instat/static/InstatObject/R/InstallPackages.R
  instat/static/InstatObject/R/install_packages.R
Labels: feature

#8117 Ensured output from Correlation dialog is correct
  instat/dlgCorrelation.designer.vb
  instat/dlgCorrelation.vb
  instat/sdgCorrPlot.vb
Labels: bug

#8132 Improved appearance of Line Plot dialog
  instat/dlgLinePlot.designer.vb
Labels: skip-releasenotes

#8122 Added Plot Options to Box Plot dialog
  instat/dlgBoxPlot.designer.vb
  instat/dlgBoxPlot.resx
  instat/dlgBoxPlot.vb
Labels: feature

#8130 Created an empty windows form for dlgUseTable.
  instat/dlgUseTable.Designer.vb
  instat/dlgUseTable.resx
  instat/dlgUseTable.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#8060 Added new Export Data for Climsoft dialog
  instat/dlgExportToClimsoft.Designer.vb
  instat/dlgExportToClimsoft.vb
  instat/frmMain.Designer.vb
Labels: feature

#8139 Added Plot Options to Bar and Pie Chart dialog
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.resx
  instat/dlgBarAndPieChart.vb
Labels: feature

#8143 Empty dialogue for issue 7950
  instat/dlgFindInVariableOrFilter.Designer.vb
  instat/dlgFindInVariableOrFilter.resx
  instat/dlgFindInVariableOrFilter.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#8102 Added List keyboard to Calculator dialog
  instat/dlgCalculator.vb
  instat/ucrCalculator.Designer.vb
  instat/ucrCalculator.resx
  instat/ucrCalculator.vb
Labels: feature

#8154 Added data export to Export for Climsoft dialog
  instat/dlgExportToClimsoft.Designer.vb
  instat/dlgExportToClimsoft.vb
Labels: feature

#8148 Ensured that Default Column and Variable Name checkbox function correctly in New DataFrame dialog
  instat/dlgNewDataFrame.vb
Labels: bug

#8072 Added editor tabs to Script window
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/dlgImportDataset.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/ucrScript.Designer.vb
  instat/ucrScript.resx
  instat/ucrScript.vb
Labels: feature

#8157 Ensured that selecting variables works correctly in Climatic > Tidy and Examine > Tidy Daily Data dialog
  instat/dlgTidyDailyData.Designer.vb
  instat/dlgTidyDailyData.vb
  instat/static/InstatObject/R/instat_object_R6.R
  instat/ucrSelector.vb
Labels: bug

#8158 Fixed Alignment issue in Text Transform dialog
  instat/dlgTransformText.Designer.vb
Labels: bug

#8161 Ensured that options to carry all/selected columns works correctly in Stack dialog
  instat/dlgStack.Designer.vb
  instat/dlgStack.vb
Labels: bug

#8121 Reset the Scrollbar position on the DataView Grid at the top when Filter is applied
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
Labels: bug

#8166 Changed grid to only update one cell if replace value is done
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/ucrDataView.vb
Labels: feature
