Repository IDEMSInternational/R-Instat, pull requests merged in 2023-04, with the labels that each got.

#8206 Fixed bug in Describe> Multivariate> Canonical Correlation Analysis dialog
  instat/dlgCanonicalCorrelationAnalysis.Designer.vb
  instat/dlgCanonicalCorrelationAnalysis.vb
  instat/instat.vbproj
  instat/sdgCanonicalCorrelation.Designer.vb
  instat/sdgCanonicalCorrelation.resx
  instat/sdgCanonicalCorrelation.sw-KE.resx
  instat/sdgCanonicalCorrelation.vb
Labels: bug

#8252 Improved layout of Main Menu Toolbar
  instat/frmMain.Designer.vb
Labels: feature

#8261 New branches
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#8098 New Crowdin updates
  instat/translations/es/es_r_instat_menus.json
  instat/translations/es/es_r_instat_not_menus.json
  instat/translations/fr/fr_r_instat_menus.json
  instat/translations/fr/fr_r_instat_not_menus.json
  instat/translations/it/it_r_instat_menus.json
  instat/translations/it/it_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_menus.json
  instat/translations/pt/pt_r_instat_not_menus.json
  instat/translations/ru/ru_r_instat_menus.json
  instat/translations/ru/ru_r_instat_not_menus.json
  instat/translations/sw/sw_r_instat_menus.json
  instat/translations/sw/sw_r_instat_not_menus.json
Labels: skip-releasenotes

#8243 Ensured that 'tmin' & 'rain' fill automatically in Climatic Boxplot dialog
  instat/dlgClimaticBoxPlot.vb
Labels: feature

#8240 Ensured that 'Colour Columns by Structure' check box works correctly in Column Structure dialog
  instat/dlgColumnStructures.vb
Labels: bug

#8255 Renamed first radio button in New Data Frame dialog
  instat/dlgNewDataFrame.Designer.vb
Labels: feature

#8257 Simplified the use of comments when a data frame does not have key variables in Add Comment dialog
  instat/dlgAddComment.Designer.vb
  instat/dlgAddComment.vb
Labels: feature

#8284 Updated Help IDs for DataView
  instat/ucrDataView.vb
Labels: skip-releasenotes
