Repository IDEMSInternational/R-Instat, pull requests merged in 2023-06, with the labels that each got.

#8363 Changed default outputs maximum size to 500
  instat/clsInstatOptionsDefaults.vb
Labels: feature

#8337 Improved the Titles tab on the Graphs subdialog
  instat/clsGgplotDefaults.vb
  instat/sdgPlots.Designer.vb
  instat/sdgPlots.resx
  instat/sdgPlots.vb
Labels: feature

#8354 Added new dialog to edit cell contents in Data View
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/dlgEdit.Designer.vb
  instat/dlgEdit.resx
  instat/dlgEdit.vb
  instat/instat.vbproj
  instat/ucrDataView.Designer.vb
  instat/ucrDataView.vb
Labels: feature

#8359 Improved usability of Toolbar
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#8370 Added a layer parameter for density ridges gradient
  instat/ucrGeom.vb
Labels: feature

#8369 Improved Climatic >Inventory dialog
  instat/dlgInventoryPlot.vb
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: feature

#8358 New Crowdin updates
  instat/translations/es/es_r_instat_menus.json
  instat/translations/es/es_r_instat_not_menus.json
  instat/translations/pt/pt_r_instat_menus.json
Labels: skip-releasenotes

#8376 Fixed a bug in the SPI dialog
  instat/dlgSPI.Designer.vb
  instat/dlgSPI.vb
Labels: bug

#8381 Ensured correct default for 'Maximum Factor Levels Shown', in Describe>One variable>Summaries dialog
  instat/dlgOneVariableSummarise.vb
Labels: bug

#8385 Split the Climatic > Tidy and Examine menu; and added Pivot Table to the Climatic > Tidy and Explore menu
  instat/dlgThreeVariablePivotTable.Designer.vb
  instat/dlgThreeVariablePivotTable.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#8399 Ensured that cells can be deleted correctly in Climatic Data Entry dialog
  instat/sdgClimaticDataEntry.Designer.vb
  instat/sdgClimaticDataEntry.vb
Labels: bug

#8402 Added empty dialog in frmMain
  instat/dlgSurvey.Designer.vb
  instat/dlgSurvey.resx
  instat/dlgSurvey.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
  instat/instat.vbproj
Labels: skip-releasenotes

#8403 Renamed Minor Grid line Frame Strings in sdgThemes and sdgThemesSub
  instat/sdgThemes.vb
  instat/sdgThemesSub.Designer.vb
  instat/sdgThemesSub.vb
Labels: skip-releasenotes

#8398 Ensured that If a variable is deleted, and the variable is part of a key, then the key is also deleted
  instat/dlgDeleteRowsOrColums.Designer.vb
  instat/dlgDeleteRowsOrColums.vb
  instat/static/InstatObject/R/data_object_R6.R
Labels: bug

#8375 Ensured that Stem and Leaf plots work correctly in Describe > One Variable > Frequencies dialog
  instat/dlgOneWayFrequencies.Designer.vb
  instat/dlgOneWayFrequencies.vb
  instat/sdgOneWayFrequencies.vb
Labels: bug
