Repository IDEMSInternational/R-Instat, pull requests merged in 2023-08, with the labels that each got.

#7519 Added Random Split dialog
  instat/dlgCopySheet.Designer.vb
  instat/dlgRandomSplit.Designer.vb
  instat/dlgRandomSplit.vb
  instat/frmMain.Designer.vb
Labels: feature

#8463 Added find feature to Select option in Find dialog
  instat/Interface/IDataViewGrid.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/dlgFindInVariableOrFilter.Designer.vb
  instat/dlgFindInVariableOrFilter.resx
  instat/dlgFindInVariableOrFilter.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrDataView.vb
Labels: feature

#8470 Ensured position works correctly in Calculator dialog
  instat/dlgCalculator.vb
  instat/sdgSaveColumnPosition.vb
  instat/ucrInputComboBox.vb
  instat/ucrInputTextBox.vb
  instat/ucrSave.vb
  instat/ucrVariablename.vb
Labels: bug

#8462 Improved Describe>General menu and Describe<Graph options
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#8461 Allow R script key words to be used in Log/Script window
  instat/Model/Output/clsOutputElement.vb
  instat/clsRLink.vb
Labels: bug

#8480 Added a copy of Pivot Tables to the Prepare > Check Data menu
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#8482 Bug fix when wrapping or unwrapping a list column
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
Labels: bug

#8481 Improved Titles options in Plots subdialog
  instat/sdgPlots.Designer.vb
  instat/sdgPlots.vb
Labels: feature

#8484 Added dropdown buttons to Output Window to show/hide R commands/comments
  instat/clsInstatOptions.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#8493 Deleted unused items in the Edit menu
  instat/dlgFindInVariableOrFilter.Designer.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: bug

#8492 Improved the Describe>General and Describe>Graph menus
  instat/dlgGeneralForGraphics.Designer.vb
  instat/frmMain.Designer.vb
  instat/frmMain.vb
Labels: feature

#8495 Added rsplit package to R-instat
  instat/static/InstatObject/R/install_packages.R
Labels: skip-releasenotes

#8446 Reset the Multiple Receiver when re-opening the dialog
  instat/ucrReceiverMultiple.vb
Labels: skip-releasenotes

#8502 Ensured correct R code generated by File > New Data frame
  instat/dlgNewDataFrame.vb
Labels: bug
