Repository IDEMSInternational/R-Instat, pull requests merged in 2023-05, with the labels that each got.

#8294 Design changes in Bar chart
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.vb
Labels: skip-releasenotes

#8295 Ensure that list of last 10 opened dialogs is displayed in correct language
  instat/Translations.vb
Labels: bug

#8302 Ensured that Element field can be changed in Climatic Boxplot dialog
  instat/dlgClimaticBoxPlot.vb
Labels: bug

#8289 Added a layer parameter for density ridges
  instat/ucrGeom.vb
Labels: feature

#8259 Changed mmtable2() to gt() in Describe < Tables dialog
  instat/dlgSummaryTables.Designer.vb
  instat/dlgSummaryTables.resx
  instat/dlgSummaryTables.vb
Labels: feature

#8027 Added options in New Themes subdialog for frequency and summary tables.
  instat/dlgSummaryTables.vb
  instat/sdgFormatSummaryTables.Designer.vb
  instat/sdgFormatSummaryTables.vb
  instat/sdgSummaryThemes.Designer.vb
  instat/sdgSummaryThemes.vb
Labels: feature

#8311 Added tooltip text from VB Designer files
  instat/translations/en/r_instat_not_menus.json
Labels: skip-releasenotes

#8317 New Crowdin updates
  instat/translations/pt/pt_r_instat_not_menus.json
Labels: skip-releasenotes

#8318 Added drop variables feature to Stack(Pivot Longer) dialog
  instat/dlgStack.Designer.vb
  instat/dlgStack.vb
Labels: feature

#8322 Improved layout of New Data Frame dialog
  instat/dlgNewDataFrame.Designer.vb
Labels: feature

#8328 Add version number back in
  instat/frmMain.Designer.vb
Labels: skip-releasenotes

#8326 Improved the back-to-back charts in the Bar Chart dialog
  instat/dlgBarAndPieChart.vb
Labels: feature

#8327 Ensured that R script generated by Climatic Summary dialog is correct
  instat/dlgClimaticSummary.vb
Labels: bug

#8329 Ensured that Import Dataset dialog does not hang when opened in French
  instat/dlgImportDataset.vb
Labels: bug

#8316 Ensured that Bar Chart dialog opens with the correct settings, and improved formatting
  instat/dlgBarAndPieChart.Designer.vb
  instat/dlgBarAndPieChart.vb
  instat/sdgPlots.vb
Labels: bug

#8305 Add label options to the Mapping dialog
  instat/dlgClimaticStationMaps.Designer.vb
  instat/dlgClimaticStationMaps.vb
  instat/ucrGeom.vb
Labels: feature

#8334 Enabled plot options in Line Plot dialog.
  instat/dlgLinePlot.vb
Labels: feature

#8145 Added a Use Table dialog
  instat/dlgSummaryTables.vb
  instat/dlgUseTable.Designer.vb
  instat/dlgUseTable.vb
  instat/frmMain.Designer.vb
  instat/sdgFormatSummaryTables.vb
Labels: feature

#8330 Changed underlying R function in dlgOneVariable Summarise > customised tab (from mmtable function to gt function)
  instat/dlgOneVariableSummarise.Designer.vb
  instat/dlgOneVariableSummarise.vb
Labels: feature
