Repository IDEMSInternational/R-Instat, pull requests merged in 2023-07, with the labels that each got.

#8412 Ensured that stem and leaf fields set correctly when opening One Way Frequencies dialog for first time
  instat/dlgOneWayFrequencies.vb
Labels: bug

#8418 Ensured that insert/delete row in Data grid does not trigger jump to the top of the page
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
Labels: bug

#8367 Improved the column right-click menu and the Edit Cell dialog
  instat/Interface/IDataViewGrid.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/dlgEdit.Designer.vb
  instat/dlgEdit.vb
  instat/ucrDataView.vb
  instat/ucrInputFactorLevels.vb
  instat/ucrReceiver.vb
  instat/ucrSelector.vb
Labels: feature

#8425 Added tooltips to selected dialogs in the Describe menu
  instat/frmMain.Designer.vb
Labels: feature

#8422 Ensured that columns in the Data Grid can be deleted even when there are no key columns
  instat/static/InstatObject/R/data_object_R6.R
Labels: bug

#8405 Ensured that Script window short cut keys work correctly
  instat/ucrScript.vb
Labels: bug

#8429 Restores 'add to' and 'save' output window features
  instat/Model/Output/clsOutputLogger.vb
  instat/UserControl/ucrOutputPage.vb
  instat/UserControl/ucrOutputPages.vb
Labels: bug

#8419 Fixed calculating column summaries with a missing-proportion option
  instat/static/InstatObject/R/Backend_Components/summary_functions.R
Labels: bug

#8431 Ensured that Pivot Table dialog in Climatic menu puts the factor variable in the right order
  instat/dlgThreeVariablePivotTable.vb
Labels: bug

#8424 Ensured that Title values does not reset to default when changed in Plots sub dialog
  instat/sdgPlots.vb
Labels: bug

#8426 Implemented Find Row(s) in the Data View Grid and fixed bug in the Edit Cell dialog
  instat/Interface/IDataViewGrid.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrReoGrid.vb
  instat/dlgFindInVariableOrFilter.Designer.vb
  instat/dlgFindInVariableOrFilter.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrDataView.vb
Labels: feature

#8437 Ensured that the Change of the Data Frame Works correctly in the Pivot Table dialog in Climatic Menu
  instat/dlgThreeVariablePivotTable.vb
Labels: skip-releasenotes

#8449 Added Colour and Fill options for density ridges
  instat/ucrGeom.vb
Labels: feature

#8445 Fixed error message in Climatic > Check Data > Inventory dialog
  instat/dlgInventoryPlot.vb
Labels: bug

#8447 Implemented wrapping and unwrapping on the DataView Grid
  instat/Interface/IDataViewGrid.vb
  instat/Model/DataFrame/clsDataFramePage.vb
  instat/UserControls/DataGrid/Linux/ucrDataViewLinuxGrid.vb
  instat/UserControls/DataGrid/ReoGrid/ucrDataViewReoGrid.vb
  instat/dlgWordwrap.Designer.vb
  instat/dlgWordwrap.vb
  instat/frmMain.Designer.vb
  instat/static/InstatObject/R/data_object_R6.R
  instat/static/InstatObject/R/instat_object_R6.R
  instat/static/InstatObject/R/stand_alone_functions.R
  instat/ucrDataView.vb
Labels: feature

#8430 Added Help Button to Maximise window and Output window
  instat/UserControl/ucrOutputPages.Designer.vb
  instat/UserControl/ucrOutputPages.resx
  instat/UserControl/ucrOutputPages.vb
  instat/UserControls/frmMaximiseOutput.Designer.vb
  instat/UserControls/frmMaximiseOutput.vb
Labels: feature
