Repository IDEMSInternational/R-Instat, pull requests merged in 2025-05, with the labels that each got.

#9560 Added the tricot dialog: Modelling (tree)
  instat/dlgModellingTree.Designer.vb
  instat/dlgModellingTree.vb
Labels: Tricot Analysis

#9559 Small Change in No Cavariate Tricot Dialog
  instat/dlgPlacketLuceModel.vb
  instat/sdgDisplayModelOptions.Designer.vb
  instat/sdgDisplayModelOptions.vb
Labels: Tricot Analysis

#9584 Edits/Examine Submenu in Tricot
  instat/dlgDefineTricotData.Designer.vb
  instat/dlgDefineTricotData.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: Tricot Analysis

#9582 Adding checks for the Define Tricots Dialog
  instat/dlgDefineTricotData.vb
Labels: Tricot Analysis

#9577 Transform Tricot Data
  instat/dlgTransformTricotData.Designer.vb
  instat/dlgTransformTricotData.vb
  instat/sdgTransformations.Designer.vb
  instat/sdgTransformations.vb
  instat/ucrReceiver.vb
Labels: Tricot Analysis

#9647 Changes to the Tricots Menu Layout
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
Labels: feature

#9671 Added cross-platform script generation to Tricot/Describe/Correlations
  instat/clsTransformationRModel.vb
  instat/dlgTraitCorrelationsXp.Designer.vb
  instat/dlgTraitCorrelationsXp.resx
  instat/dlgTraitCorrelationsXp.vb
  instat/frmMain.Designer.vb
  instat/frmMain.resx
  instat/frmMain.vb
  instat/instat.vbproj
  instat/packages.config
  instat/static/DialogDefinitions/DlgTraitCorrelations/dlgTraitCorrelations.R
  instat/static/DialogDefinitions/DlgTraitCorrelations/dlgTraitCorrelations.json
  instat/ucrReceiverMultiple.vb
Labels: enhancement

#9689 added ncdf4 do install from archive
  instat/static/InstatObject/R/InstallPackages.R
Labels: skip-releasenotes

#9690 updated install packages
  instat/static/InstatObject/R/InstallPackages.R
Labels: skip-releasenotes

#9691 Update InstallPackages.R
  instat/static/InstatObject/R/InstallPackages.R
Labels: skip-releasenotes
